import fs from 'node:fs';
import http from 'node:http';
import os from 'node:os';
import path from 'node:path';
import { execFile, spawn } from 'node:child_process';
import { promisify } from 'node:util';
import {
  createHash, createHmac, createPrivateKey, createPublicKey, generateKeyPairSync,
  randomBytes, sign, timingSafeEqual, verify
} from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { buildDockerRunnerArgs } from '../api/src/clean/runner-adapters.mjs';
import { buildDockerParserArgs } from '../api/src/clean/parser-docker.mjs';
import { validateRunnerJobSpec, validateRunnerReceipt } from '../api/src/clean/runner-protocol.mjs';
import {
  EVIDENCE_ASSET_VERSION, PARSER_RECEIPT_VERSION, signParserReceipt, verifyParserJob
} from '../api/src/clean/parser-protocol.mjs';

const execFileAsync = promisify(execFile);
const WINDOW_MS = 60_000;
const TERMINAL = new Set(['succeeded', 'failed', 'cancelled', 'expired', 'external_result_unknown']);
const PARSER_TERMINAL = new Set(['parsed', 'unsupported', 'invalid', 'resource_exceeded', 'failed', 'cancelled', 'external_result_unknown']);
const DEFAULT_PARSER_DIGEST = 'sha256:bc69569bc471a27833b7f1174ac1634b5760614c6742237c443641ac5da808e4';

export function createCleanBroker(options = {}) {
  const host = String(options.host || process.env.AIWS_BROKER_HOST || '127.0.0.1'); if (!['127.0.0.1', '::1', 'localhost', '0.0.0.0'].includes(host)) throw new Error('clean_broker_bind_host_invalid');
  const port = Number(options.port ?? process.env.AIWS_BROKER_PORT ?? 4322); const secret = String(options.secret || process.env.AIWS_RUNNER_BROKER_SECRET || readSecretFile(process.env.AIWS_BROKER_HMAC_SECRET_FILE) || ''); if (secret.length < 16) throw new Error('clean_broker_secret_required');
  const runnerDigest = String(options.runnerDigest || process.env.AIWS_RUNNER_DIGEST || '').toLowerCase(); if (!/^sha256:[a-f0-9]{64}$/.test(runnerDigest)) throw new Error('clean_broker_digest_required');
  const parserDigest = String(options.parserDigest || process.env.AIWS_PARSER_IMAGE_DIGEST || DEFAULT_PARSER_DIGEST).toLowerCase(); if (!/^sha256:[a-f0-9]{64}$/.test(parserDigest)) throw new Error('clean_parser_digest_required');
  const stateRoot = path.resolve(options.stateRoot || process.env.AIWS_BROKER_STATE || path.join(os.homedir(), '.ai-workspace', 'clean-runner-broker')); fs.mkdirSync(path.join(stateRoot, 'jobs'), { recursive: true, mode: 0o700 }); fs.mkdirSync(path.join(stateRoot, 'parser-jobs'), { recursive: true, mode: 0o700 });
  const identity = loadIdentity(stateRoot); const jobs = loadJobs(stateRoot); const parserJobs = loadParserJobs(stateRoot); const nonces = new Map(); const children = new Map(); const parserChildren = new Map(); const spawnImpl = options.spawnImpl || spawn;
  const executeFile = options.execFileImpl || execFileAsync;

  async function probe() { const result = await executeFile('docker', ['version', '--format', '{{.Server.Version}}'], { encoding: 'utf8', timeout: 10_000, windowsHide: true, maxBuffer: 64 * 1024 }); return { schema_version: 'aiws.clean-broker.probe.v2', status: 'ready', docker_server_version: String(result.stdout || '').trim(), runner_digest: runnerDigest, parser_digest: parserDigest, identity_public_key: identity.publicKey, capabilities: ['digest-pinned', 'cap-drop-all', 'read-only-root', 'no-new-privileges', 'bounded-tmpfs', 'bounded-network', 'parser-job-v1', 'parser-restart-reconciliation'] }; }

  async function handler(req, res) {
    try {
      const url = new URL(req.url || '/', 'http://127.0.0.1'); if (req.method === 'GET' && url.pathname === '/livez') return send(res, 200, { status: 'live', process: 'v3-clean-runner-broker' });
      const parserRoute = url.pathname.startsWith('/internal/v2/parser-jobs');
      const body = await readBody(req, parserRoute ? 36 * 1024 * 1024 : 1024 * 1024); authenticate(req.headers, req.method || 'GET', url.pathname, body.raw, secret, nonces);
      if (req.method === 'GET' && url.pathname === '/internal/v2/probe') return send(res, 200, await probe());
      if (req.method === 'GET' && url.pathname === '/internal/v2/parser-jobs/probe') return send(res, 200, await probe());
      if (req.method === 'POST' && url.pathname === '/internal/v2/parser-jobs') {
        const envelope = body.value || {}; const verified = verifyParserJob(envelope.job, envelope.signature, String(envelope.service_public_key || ''), { expectedImageDigest: parserDigest, now: Date.now() });
        if (options.servicePublicKey && String(envelope.service_public_key || '').trim() !== String(options.servicePublicKey).trim()) throw brokerError('parser_signature_invalid', 403);
        const input = strictBase64(envelope.input_base64); if (input.byteLength !== verified.job.input_bytes || hash(input) !== verified.job.input_sha256 || hash(input) !== verified.job.input_cas_sha256) throw brokerError('parser_input_mismatch', 409);
        const prior = [...parserJobs.values()].find((item) => item.job.parser_job_id === verified.job.parser_job_id); if (prior) { if (prior.job_hash !== verified.job_sha256) throw brokerError('parser_job_conflict', 409); return send(res, 200, publicParserJob(prior)); }
        const jobId = `broker_parser_job_${randomBytes(16).toString('hex')}`; const parserJob = { job_id: jobId, status: 'queued', job: verified.job, job_hash: verified.job_sha256, created_at: new Date().toISOString(), receipt: null, signature: null, signer_public_key: identity.publicKey }; parserJobs.set(jobId, parserJob); prepareParserFiles(stateRoot, parserJob, input); persistParserJob(stateRoot, parserJob); input.fill(0); queueMicrotask(() => executeParser(parserJob).catch(() => undefined)); return send(res, 201, publicParserJob(parserJob));
      }
      const parserMatch = url.pathname.match(/^\/internal\/v2\/parser-jobs\/([^/]+)(?:\/(cancel))?$/); if (parserMatch) {
        const id = decodeURIComponent(parserMatch[1]); let parserJob = parserJobs.get(id); if (!parserJob) return send(res, 200, { job_id: id, status: 'unknown' });
        if (req.method === 'GET' && !parserMatch[2]) { if (!PARSER_TERMINAL.has(parserJob.status) && !parserChildren.has(id)) parserJob = await reconcileParser(parserJob); return send(res, 200, publicParserJob(parserJob)); }
        if (req.method === 'POST' && parserMatch[2] === 'cancel') { if (!PARSER_TERMINAL.has(parserJob.status)) { parserJob.status = 'cancelled'; terminate(parserChildren.get(id)); await executeFile('docker', ['rm', '--force', parserContainerName(parserJob)], { windowsHide: true, timeout: 10_000 }).catch(() => undefined); finishParser(parserJob, { status: 'cancelled', error_code: 'parser_cancelled', outputs: [], started_at: parserJob.started_at || parserJob.created_at, finished_at: new Date().toISOString() }); } return send(res, 200, publicParserJob(parserJob)); }
      }
      if (req.method === 'POST' && url.pathname === '/internal/v2/jobs') {
        const envelope = body.value || {}; const spec = validateRunnerJobSpec(envelope.spec, { expectedImageDigest: runnerDigest }); const specJson = canonical(spec); const publicKey = String(envelope.service_public_key || '');
        if (!publicKey || (options.servicePublicKey && publicKey.trim() !== String(options.servicePublicKey).trim()) || !verify(null, Buffer.from(specJson), createPublicKey(publicKey), Buffer.from(String(envelope.signature || ''), 'base64url'))) throw brokerError('runner_signature_invalid', 403);
        const specHash = hash(specJson); const prior = [...jobs.values()].find((item) => item.spec.job_spec_id === spec.job_spec_id); if (prior) { if (prior.spec_hash !== specHash) throw brokerError('runner_job_conflict', 409); return send(res, 200, publicJob(prior)); }
        const jobId = `broker_job_${randomBytes(16).toString('hex')}`; const job = { job_id: jobId, status: 'queued', spec, spec_hash: specHash, created_at: new Date().toISOString(), receipt: null, signature: null, signer_public_key: identity.publicKey }; jobs.set(jobId, job); persistJob(stateRoot, job); queueMicrotask(() => execute(job).catch(() => undefined)); return send(res, 201, publicJob(job));
      }
      const match = url.pathname.match(/^\/internal\/v2\/jobs\/([^/]+)(?:\/(cancel))?$/); if (match) {
        const id = decodeURIComponent(match[1]); let job = jobs.get(id); if (!job) return send(res, 200, { job_id: id, status: 'unknown' });
        if (req.method === 'GET' && !match[2]) { if (!TERMINAL.has(job.status) && !children.has(id)) job = await reconcile(job); return send(res, 200, publicJob(job)); }
        if (req.method === 'POST' && match[2] === 'cancel') { if (!TERMINAL.has(job.status)) { job.status = 'cancelled'; terminate(children.get(id)); await executeFile('docker', ['rm', '--force', containerName(job)], { windowsHide: true, timeout: 10_000 }).catch(() => undefined); finish(job, 'cancelled', null, Buffer.alloc(0), Buffer.alloc(0), 'cancelled'); } return send(res, 200, publicJob(job)); }
      }
      return send(res, 404, { error: { code: 'not_found' } });
    } catch (error) { return send(res, Number(error?.status || 500), { error: { code: String(error?.code || 'internal_error'), message: String(error?.message || 'internal error').slice(0, 160), details: error?.details || {} } }); }
  }

  async function execute(job) {
    if (job.status === 'cancelled') return; job.status = 'running'; job.started_at = new Date().toISOString(); persistJob(stateRoot, job);
    const args = buildDockerRunnerArgs(job.spec, { image: runnerDigest, dataVolume: options.dataVolume || process.env.AIWS_CLEAN_DATA_VOLUME || 'aiws-clean-data' }); const stdout = []; const stderr = [];
    try { const child = spawnImpl('docker', args, { stdio: ['ignore', 'pipe', 'pipe'], windowsHide: true }); children.set(job.job_id, child); child.stdout?.on('data', (chunk) => pushBounded(stdout, chunk)); child.stderr?.on('data', (chunk) => pushBounded(stderr, chunk)); const deadline = Math.max(1, Date.parse(job.spec.deadline_at) - Date.now()); const timer = setTimeout(() => { job.timed_out = true; terminate(child); }, deadline); timer.unref?.(); const result = await new Promise((resolve, reject) => { child.once('error', reject); child.once('exit', (code) => resolve({ code })); }); clearTimeout(timer); const status = job.status === 'cancelled' ? 'cancelled' : job.timed_out ? 'expired' : result.code === 0 ? 'succeeded' : 'failed'; finish(job, status, result.code, Buffer.concat(stdout), Buffer.concat(stderr), status === 'expired' ? 'runner_deadline_exceeded' : status === 'failed' ? 'runner_failed' : ''); }
    catch (error) { finish(job, job.status === 'cancelled' ? 'cancelled' : 'failed', 1, Buffer.concat(stdout), Buffer.concat(stderr), String(error?.code || 'runner_spawn_failed')); }
    finally { children.delete(job.job_id); }
  }

  async function executeParser(parserJob) {
    if (parserJob.status === 'cancelled') return; parserJob.status = 'running'; parserJob.started_at = new Date().toISOString(); persistParserJob(stateRoot, parserJob);
    try {
      let result;
      if (typeof options.parserExecute === 'function') result = await options.parserExecute(parserJob.job, { input: fs.readFileSync(parserInputFile(stateRoot, parserJob)), outputRoot: parserOutputRoot(stateRoot, parserJob) });
      else {
        const args = buildDockerParserArgs(parserJob.job, { image: parserDigest, inputFile: parserInputFile(stateRoot, parserJob), jobFile: parserJobFile(stateRoot, parserJob), outputRoot: parserOutputRoot(stateRoot, parserJob) });
        const child = spawnImpl('docker', args, { stdio: ['ignore', 'pipe', 'pipe'], windowsHide: true }); parserChildren.set(parserJob.job_id, child); const stderr = []; child.stderr?.on('data', (chunk) => pushBounded(stderr, chunk)); const deadline = Math.max(1, Date.parse(parserJob.job.deadline_at) - Date.now()); const timer = setTimeout(() => { parserJob.timed_out = true; terminate(child); }, deadline); timer.unref?.(); const exit = await new Promise((resolve, reject) => { child.once('error', reject); child.once('exit', (code) => resolve(Number(code))); }); clearTimeout(timer);
        if (parserJob.status === 'cancelled') return; if (parserJob.timed_out) result = { status: 'resource_exceeded', error_code: 'parser_deadline_exceeded', outputs: [], started_at: parserJob.started_at, finished_at: new Date().toISOString() };
        else if (exit !== 0) result = { status: 'failed', error_code: 'parser_worker_failed', outputs: [], started_at: parserJob.started_at, finished_at: new Date().toISOString() };
        else result = readParserWorkerResult(stateRoot, parserJob);
      }
      if (!PARSER_TERMINAL.has(parserJob.status)) finishParser(parserJob, materializeParserResult(stateRoot, parserJob, result));
    } catch (error) { if (!PARSER_TERMINAL.has(parserJob.status)) finishParser(parserJob, { status: 'failed', error_code: String(error?.code || 'parser_spawn_failed'), outputs: [], started_at: parserJob.started_at, finished_at: new Date().toISOString() }); }
    finally { parserChildren.delete(parserJob.job_id); }
  }

  function finishParser(parserJob, result) {
    const outputs = validateParserResultFiles(stateRoot, parserJob, result); const manifest = { schema_version: EVIDENCE_ASSET_VERSION, outputs: outputs.map(({ file, metadata, ...item }) => item) }; const receipt = { schema_version: PARSER_RECEIPT_VERSION, receipt_id: `parser_receipt_${randomBytes(16).toString('hex')}`, parser_job_id: parserJob.job.parser_job_id, parser_run_ref: parserJob.job.parser_run_ref, job_sha256: parserJob.job_hash, status: String(result.status || 'failed'), input_sha256: parserJob.job.input_sha256, format_sha256: parserJob.job.format_sha256, limits_sha256: parserJob.job.limits_sha256, checkpoint_token_hash: parserJob.job.checkpoint_token_hash, output_manifest: manifest, output_manifest_sha256: hash(canonical(manifest)), error_code: String(result.error_code || ''), started_at: result.started_at || parserJob.started_at || parserJob.created_at, finished_at: result.finished_at || new Date().toISOString() }; const signed = signParserReceipt(receipt, identity.privateKey, { expectedJobId: parserJob.job.parser_job_id, expectedJobHash: parserJob.job_hash, expectedInputHash: parserJob.job.input_sha256, expectedFormatHash: parserJob.job.format_sha256, expectedLimitsHash: parserJob.job.limits_sha256, expectedCheckpointHash: parserJob.job.checkpoint_token_hash }); parserJob.status = signed.receipt.status; parserJob.receipt = signed.receipt; parserJob.signature = signed.signature; parserJob.outputs = outputs; parserJob.finished_at = signed.receipt.finished_at; persistParserJob(stateRoot, parserJob);
  }

  async function reconcileParser(parserJob) { try { const result = await executeFile('docker', ['inspect', '--format', '{{.State.Status}} {{.State.ExitCode}}', parserContainerName(parserJob)], { encoding: 'utf8', timeout: 10_000, windowsHide: true, maxBuffer: 64 * 1024 }); const [status, code] = String(result.stdout || '').trim().split(/\s+/, 2); if (status === 'running') return parserJob; if (['exited', 'dead'].includes(status) && Number(code) === 0 && fs.existsSync(path.join(parserOutputRoot(stateRoot, parserJob), 'result.json'))) finishParser(parserJob, readParserWorkerResult(stateRoot, parserJob)); else finishParser(parserJob, { status: 'external_result_unknown', error_code: 'parser_external_result_unknown', outputs: [], started_at: new Date().toISOString(), finished_at: new Date().toISOString() }); } catch { finishParser(parserJob, { status: 'external_result_unknown', error_code: 'parser_external_result_unknown', outputs: [], started_at: new Date().toISOString(), finished_at: new Date().toISOString() }); } return parserJob; }

  function finish(job, status, exitCode, stdout, stderr, errorCode) { const finished = new Date().toISOString(); const outputs = job.spec.output_paths || []; const receipt = validateRunnerReceipt({ schema_version: 'runner.receipt.v2', receipt_id: `broker_receipt_${randomBytes(16).toString('hex')}`, job_spec_id: job.spec.job_spec_id, job_spec_hash: job.spec_hash, runner_profile_ref: job.spec.runner_profile_ref, runner_job_ref: job.job_id, status, exit_code: exitCode, stdout_sha256: stdout.length ? hash(stdout) : '', stderr_sha256: stderr.length ? hash(stderr) : '', output_sha256: outputs.length ? hash(canonical(outputs)) : '', stdout_bytes: stdout.length, stderr_bytes: stderr.length, output_bytes: 0, output_paths: outputs, error_code: errorCode, started_at: job.started_at || job.created_at, finished_at: finished }); const json = canonical(receipt); job.status = status; job.receipt = receipt; job.signature = sign(null, Buffer.from(json), identity.privateKey).toString('base64url'); job.finished_at = finished; persistJob(stateRoot, job); }
  async function reconcile(job) { try { const result = await executeFile('docker', ['inspect', '--format', '{{.State.Status}} {{.State.ExitCode}}', containerName(job)], { encoding: 'utf8', timeout: 10_000, windowsHide: true, maxBuffer: 64 * 1024 }); const [status, code] = String(result.stdout || '').trim().split(/\s+/, 2); if (status === 'running') return job; if (['exited', 'dead'].includes(status)) finish(job, Number(code) === 0 ? 'succeeded' : 'failed', Number(code), Buffer.alloc(0), Buffer.alloc(0), Number(code) === 0 ? '' : 'runner_failed'); else job.status = 'external_result_unknown'; } catch { job.status = 'external_result_unknown'; persistJob(stateRoot, job); } return job; }
  async function close() { for (const [id, child] of children) { terminate(child); const job = jobs.get(id); if (job && !TERMINAL.has(job.status)) finish(job, 'cancelled', null, Buffer.alloc(0), Buffer.alloc(0), 'broker_shutdown'); } children.clear(); for (const [id, child] of parserChildren) { terminate(child); const job = parserJobs.get(id); if (job && !PARSER_TERMINAL.has(job.status)) finishParser(job, { status: 'cancelled', error_code: 'broker_shutdown', outputs: [], started_at: job.started_at || job.created_at, finished_at: new Date().toISOString() }); } parserChildren.clear(); }
  return { host, port, stateRoot, runnerDigest, parserDigest, jobs, parserJobs, identity_public_key: identity.publicKey, handler, probe, close };
}

export async function start(options = {}) { const app = createCleanBroker(options); const server = http.createServer((req, res) => void Promise.resolve(app.handler(req, res))); await new Promise((resolve) => server.listen(app.port, app.host, resolve)); const address = server.address(); return { ...app, server, url: `http://${address.address}:${address.port}`, close: async () => { await app.close(); await new Promise((resolve) => server.close(resolve)); } }; }

function authenticate(headers, method, route, raw, secret, nonces) { const timestamp = String(headers['x-aiws-timestamp'] || ''); const nonce = String(headers['x-aiws-nonce'] || ''); const bodyHash = String(headers['x-aiws-body-sha256'] || ''); const signature = String(headers['x-aiws-signature'] || ''); if (!/^\d{13}$/.test(timestamp) || Math.abs(Date.now() - Number(timestamp)) > WINDOW_MS || !/^[A-Za-z0-9_-]{16,160}$/.test(nonce) || !/^[a-f0-9]{64}$/.test(bodyHash) || hash(raw) !== bodyHash) throw brokerError('broker_signature_invalid', 401); for (const [key, value] of nonces) if (value < Date.now() - WINDOW_MS) nonces.delete(key); if (nonces.has(nonce)) throw brokerError('broker_nonce_replay', 409); const expected = createHmac('sha256', secret).update(`${method}\n${route}\n${timestamp}\n${nonce}\n${bodyHash}`).digest('hex'); if (!safeEqual(signature, expected)) throw brokerError('broker_signature_invalid', 401); nonces.set(nonce, Number(timestamp)); }
async function readBody(req, maximum = 1024 * 1024) { const chunks = []; let size = 0; for await (const chunk of req) { size += chunk.length; if (size > maximum) throw brokerError('body_too_large', 413); chunks.push(chunk); } const raw = size ? Buffer.concat(chunks).toString('utf8') : canonical({}); try { return { raw, value: size ? JSON.parse(raw) : {} }; } catch { throw brokerError('invalid_json', 400); } }
function loadIdentity(root) { const file = path.join(root, 'identity.json'); if (fs.existsSync(file)) { const value = JSON.parse(fs.readFileSync(file, 'utf8')); return { publicKey: value.public_key, privateKey: createPrivateKey(value.private_key) }; } const pair = generateKeyPairSync('ed25519'); const value = { public_key: pair.publicKey.export({ type: 'spki', format: 'pem' }).toString(), private_key: pair.privateKey.export({ type: 'pkcs8', format: 'pem' }).toString() }; fs.writeFileSync(file, `${JSON.stringify(value, null, 2)}\n`, { mode: 0o600, flag: 'wx' }); return { publicKey: value.public_key, privateKey: pair.privateKey }; }
function loadJobs(root) { const jobs = new Map(); for (const name of fs.readdirSync(path.join(root, 'jobs')).filter((item) => /^broker_job_[A-Za-z0-9]+\.json$/.test(item))) { try { const value = JSON.parse(fs.readFileSync(path.join(root, 'jobs', name), 'utf8')); jobs.set(value.job_id, value); } catch { /* a corrupt local state record reconciles as unknown */ } } return jobs; }
function loadParserJobs(root) { const jobs = new Map(); for (const directory of fs.readdirSync(path.join(root, 'parser-jobs'), { withFileTypes: true }).filter((item) => item.isDirectory() && /^broker_parser_job_[A-Za-z0-9]+$/.test(item.name))) { try { const value = JSON.parse(fs.readFileSync(path.join(root, 'parser-jobs', directory.name, 'journal.json'), 'utf8')); jobs.set(value.job_id, value); } catch { /* a corrupt parser journal is not trusted */ } } return jobs; }
function persistJob(root, job) { const safe = { ...job, child: undefined }; const file = path.join(root, 'jobs', `${job.job_id}.json`); const temp = `${file}.${process.pid}.tmp`; fs.writeFileSync(temp, `${JSON.stringify(safe, null, 2)}\n`, { mode: 0o600 }); fs.renameSync(temp, file); }
function persistParserJob(root, job) { const safe = { ...job, outputs: (job.outputs || []).map(({ metadata, ...value }) => ({ ...value, metadata })) }; const file = path.join(parserJobRoot(root, job), 'journal.json'); const temp = `${file}.${process.pid}.tmp`; fs.writeFileSync(temp, `${JSON.stringify(safe, null, 2)}\n`, { mode: 0o600 }); if (fs.existsSync(file)) fs.rmSync(file, { force: true }); fs.renameSync(temp, file); }
function prepareParserFiles(root, job, input) { const directory = parserJobRoot(root, job); fs.mkdirSync(parserOutputRoot(root, job), { recursive: true, mode: 0o700 }); job.input_file = parserInputFile(root, job); job.job_file = parserJobFile(root, job); job.output_root = parserOutputRoot(root, job); fs.writeFileSync(job.input_file, input, { mode: 0o600, flag: 'wx' }); fs.writeFileSync(job.job_file, `${canonical(job.job)}\n`, { mode: 0o600, flag: 'wx' }); }
function parserJobRoot(root, job) { return path.join(root, 'parser-jobs', job.job_id); }
function parserInputFile(root, job) { return path.join(parserJobRoot(root, job), 'input.bin'); }
function parserJobFile(root, job) { return path.join(parserJobRoot(root, job), 'job.json'); }
function parserOutputRoot(root, job) { return path.join(parserJobRoot(root, job), 'outputs'); }
function readParserWorkerResult(root, job) { const value = JSON.parse(fs.readFileSync(path.join(parserOutputRoot(root, job), 'result.json'), 'utf8')); if (value.schema_version !== 'parser.worker-result.v1' || value.parser_job_id !== job.job.parser_job_id) throw brokerError('parser_worker_result_invalid', 409); return value; }
function materializeParserResult(root, job, result = {}) { const outputRoot = parserOutputRoot(root, job); const values = Array.isArray(result.outputs) ? result.outputs : []; const outputs = values.map((value, index) => { const file = String(value.file || `adapter-output-${String(index + 1).padStart(3, '0')}.bin`); if (value.bytes != null || value.content_base64 != null) { const bytes = value.bytes != null ? Buffer.from(value.bytes) : strictBase64(value.content_base64); const target = path.join(outputRoot, file); if (!fs.existsSync(target)) fs.writeFileSync(target, bytes, { mode: 0o600, flag: 'wx' }); } return { ...value, file }; }); return { ...result, started_at: result.started_at || job.started_at, finished_at: result.finished_at || new Date().toISOString(), outputs }; }
function validateParserResultFiles(root, job, result = {}) { if (!PARSER_TERMINAL.has(String(result.status || ''))) throw brokerError('parser_worker_result_invalid', 409); const values = Array.isArray(result.outputs) ? result.outputs : []; if (result.status !== 'parsed' && values.length) throw brokerError('parser_worker_result_invalid', 409); if (result.status === 'parsed' && !values.length) throw brokerError('parser_worker_result_invalid', 409); let total = 0; return values.map((value) => { const file = String(value.file || ''); if (!/^[A-Za-z0-9][A-Za-z0-9_.-]{0,127}$/.test(file)) throw brokerError('parser_output_invalid', 409); const bytes = fs.readFileSync(path.join(parserOutputRoot(root, job), file)); total += bytes.length; if (total > 104857600) throw brokerError('parser_output_too_large', 413); const metadata = value.metadata && typeof value.metadata === 'object' && !Array.isArray(value.metadata) ? value.metadata : {}; const item = { kind: String(value.kind || ''), content_sha256: hash(bytes), byte_length: bytes.length, media_type: String(value.media_type || ''), metadata_sha256: hash(canonical(metadata)) }; if (value.content_sha256 && value.content_sha256 !== item.content_sha256) throw brokerError('parser_output_tamper', 409); if (value.metadata_sha256 && value.metadata_sha256 !== item.metadata_sha256) throw brokerError('parser_output_tamper', 409); return { ...item, file, metadata }; }); }
function publicParserJob(job) { const value = { job_id: job.job_id, status: job.status }; if (!job.receipt) return value; return { ...value, receipt: job.receipt, signature: job.signature, signer_public_key: job.signer_public_key, outputs: publicParserOutputs(job, job.outputs || []) }; }
function publicParserOutputs(job, outputs) { return outputs.map(({ file, metadata, metadata_sha256: _metadataHash, ...value }) => { const candidate = job.output_root ? path.join(job.output_root, file) : null; const bytes = candidate && fs.existsSync(candidate) ? fs.readFileSync(candidate) : Buffer.alloc(0); if (hash(bytes) !== value.content_sha256) throw brokerError('parser_output_tamper', 409); return { ...value, metadata, content_base64: bytes.toString('base64') }; }); }
function strictBase64(value) { const text = String(value || ''); let bytes; try { bytes = Buffer.from(text, 'base64'); } catch { throw brokerError('invalid_base64', 400); } if (bytes.toString('base64').replace(/=+$/, '') !== text.replace(/=+$/, '')) throw brokerError('invalid_base64', 400); return bytes; }
function publicJob(job) { return { job_id: job.job_id, status: job.status, ...(job.receipt ? { receipt: job.receipt, signature: job.signature, signer_public_key: job.signer_public_key } : {}) }; }
function containerName(job) { return `aiws-${job.spec.job_spec_id}`; }
function parserContainerName(job) { return `aiws-parser-${job.job.parser_job_id}`; }
function pushBounded(chunks, chunk) { const current = chunks.reduce((total, item) => total + item.length, 0); if (current < 1024 * 1024) chunks.push(Buffer.from(chunk).subarray(0, 1024 * 1024 - current)); }
function terminate(child) { if (!child || child.exitCode != null) return; try { if (process.platform === 'win32') spawn('taskkill', ['/pid', String(child.pid), '/T', '/F'], { windowsHide: true, stdio: 'ignore' }); else process.kill(-child.pid, 'SIGTERM'); } catch { try { child.kill('SIGKILL'); } catch { /* already exited */ } } }
function send(res, status, value) { res.writeHead(status, { 'content-type': 'application/json; charset=utf-8', 'cache-control': 'no-store' }); res.end(JSON.stringify(value)); return value; }
function brokerError(code, status, details = {}) { const error = new Error(code); error.code = code; error.status = status; error.details = details; return error; }
function canonical(value) { if (value === null || typeof value !== 'object') return JSON.stringify(value); if (Array.isArray(value)) return `[${value.map((item) => canonical(item)).join(',')}]`; return `{${Object.keys(value).sort().filter((key) => value[key] !== undefined).map((key) => `${JSON.stringify(key)}:${canonical(value[key])}`).join(',')}}`; }
function hash(value) { return createHash('sha256').update(value).digest('hex'); }
function safeEqual(left, right) { const a = Buffer.from(String(left)); const b = Buffer.from(String(right)); return a.length === b.length && timingSafeEqual(a, b); }
function readSecretFile(file) { if (!file) return ''; try { return fs.readFileSync(path.resolve(String(file)), 'utf8').trim(); } catch { return ''; } }

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) { const running = await start(); process.stdout.write(`V3-Clean Runner Broker listening on ${running.url}\n`); const shutdown = async () => { await running.close(); process.exit(0); }; process.once('SIGINT', shutdown); process.once('SIGTERM', shutdown); }
