import { useEffect, useState } from 'react';
import { Check, KeyRound, RefreshCw, Search, ShieldCheck } from 'lucide-react';
import { apiV2, mutateV2 } from '../../api';

export type CodexDiscoveryProvider = { discovery_id?: string; id?: string; name?: string; provider?: string; model?: string; base_url?: string | null; has_credential?: boolean; credential_kind?: string; source_revision?: string; auth_type?: string; credential_available?: boolean };
export type CodexDiscoverySource = { source_id?: string; id?: string; type?: string; source_hint?: string; display_name?: string; status?: string; path_hint?: string; revision?: string; source_revision?: string; providers?: CodexDiscoveryProvider[]; records?: CodexDiscoveryProvider[] };
export type CodexDiscovery = { sources: CodexDiscoverySource[] };
export type CodexDiscoveryImportInput = Record<string, unknown>;

export function CodexDiscoveryPicker({ type = 'codex_home', data: initialData = null, onImport, onRefresh }: { type?: string; data?: CodexDiscovery | null; loading?: boolean; error?: string; actionError?: string; busy?: boolean; reconfigure?: boolean; onRefresh?: () => Promise<unknown>; onImport?: (input: CodexDiscoveryImportInput) => Promise<unknown> }) {
  const [data, setData] = useState<CodexDiscovery | null>(initialData); const [loading, setLoading] = useState(false); const [selected, setSelected] = useState<{ source: CodexDiscoverySource; provider: CodexDiscoveryProvider } | null>(null); const [apiKey, setApiKey] = useState(''); const [confirmed, setConfirmed] = useState(false); const refresh = async () => { setLoading(true); try { if (onRefresh) { await onRefresh(); } else { const result = await apiV2<CodexDiscovery>('/api/v2/provider-discovery/codex'); setData(result.data); } } finally { setLoading(false); } }; useEffect(() => { setData(initialData); if (!initialData) void refresh(); }, [initialData]);
  const sources = (data?.sources || []).filter((source) => !type || source.type === type || (type === 'codex_home' && source.source_hint));
  const providers = (source: CodexDiscoverySource) => source.providers || source.records || [];
  const submit = async () => { if (!selected || !confirmed) return; const record = selected.provider; const input = { source_id: selected.source.source_id || selected.source.id, source_revision: record.source_revision || selected.source.source_revision || selected.source.revision, record_id: record.id || record.discovery_id, confirmed: true, ...(record.has_credential === false || record.credential_available === false ? { api_key: apiKey } : {}) }; if (onImport) await onImport(input); else await mutateV2('/api/v2/provider-discovery/codex/import', input, 'POST', 0); setSelected(null); setApiKey(''); setConfirmed(false); };
  return <section className="discovery-picker" aria-label="本地 Codex 配置发现"><header><div><Search size={16} /><strong>读取本地 Codex 配置</strong></div><button className="button" disabled={loading} onClick={() => void refresh()}><RefreshCw className={loading ? 'spin' : ''} size={15} />刷新</button></header>{sources.map((source) => <div className="discovery-source" key={source.source_id || source.id}><div className="discovery-source-head"><span><strong>{source.display_name || source.source_hint || source.type}</strong><small>{source.path_hint || '路径已隐藏'} · {source.source_revision || source.revision || '未知'}</small></span><span className="status positive"><span />{source.status || 'ready'}</span></div>{providers(source).map((provider) => <label className="discovery-option" key={provider.discovery_id || provider.id}><input type="radio" name={`discovery-${type}`} checked={selected?.provider === provider} onChange={() => { setSelected({ source, provider }); setApiKey(''); setConfirmed(false); }} /><span><strong>{provider.name || provider.provider || provider.id}</strong><small>{provider.provider || ''} · {provider.model || '默认模型'}</small></span><span>{provider.has_credential === false || provider.credential_available === false ? <KeyRound size={14} /> : <ShieldCheck size={14} />}</span></label>)}</div>)}{!sources.length && <div className="discovery-empty"><Search size={18} />未发现此类本地配置</div>}{selected && <div className="discovery-confirm">{(selected.provider.has_credential === false || selected.provider.credential_available === false) && <label><span>API 密钥</span><input type="password" autoComplete="off" value={apiKey} onChange={(event) => setApiKey(event.target.value)} /></label>}<label><input type="checkbox" checked={confirmed} onChange={(event) => setConfirmed(event.target.checked)} /><span>确认导入所选脱敏配置</span></label><button className="button primary" disabled={!confirmed || ((selected.provider.has_credential === false || selected.provider.credential_available === false) && !apiKey)} onClick={() => void submit()}><Check size={15} />确认导入配置</button></div>}</section>;
}
