import { createPublicKey } from 'node:crypto';
import { canonicalJson, opaqueId, sha256Hex } from './canonical.mjs';
import { PlatformError } from './platform-error.mjs';
import { WindowsBridgeAdapter } from './windows-bridge-adapter.mjs';
import {
  appendAggregate, createOperation, priorResponse, requestHash,
  requireIdempotency, requirePrincipal, requireRevision, assertRevision, saveResponse, time
} from './p5-domain-helpers.mjs';

export class CleanBridgeService {
  constructor({ db, events, operations, authorization, vault, clock, adapter = null, config = {} } = {}) {
    if (!db || !events || !operations || !authorization || !vault) throw new TypeError('bridge_service_dependencies_required');
    this.db = db; this.events = events; this.operations = operations; this.authorization = authorization; this.vault = vault; this.clock = clock;
    this.adapter = adapter || new WindowsBridgeAdapter({ baseUrl: config.bridgeUrl || null, clock: () => Date.parse(time(clock)) });
  }

  list(_input = {}, principal) { requirePrincipal(principal); return { devices: this.db.query('SELECT * FROM bridge_devices WHERE actor_id=? ORDER BY updated_at DESC,id', [principal.actorId]).map(deviceView) }; }

  async pair(input = {}, principal) {
    requirePrincipal(principal); const label = bounded(input.label, 160);
    const code = input.confirmation_code == null ? null : String(input.confirmation_code); if (code != null && !/^\d{6,12}$/.test(code)) throw new PlatformError('confirmation_code_invalid', 'Bridge confirmation code is invalid', {}, 422);
    const now = time(this.clock); const key = requireIdempotency(input.idempotency_key); const hash = requestHash({ label, requested_identity_sha256: input.identity_public_key ? sha256Hex(String(input.identity_public_key)) : null, requested_transport_sha256: input.transport_public_key ? sha256Hex(String(input.transport_public_key)) : null });
    const replay = await this.db.withTransaction((tx) => priorResponse(this.operations, tx, { actorId: principal.actorId, commandId: 'bridge.pair', idempotencyKey: key, requestHash: hash, now }));
    if (replay) return replay;
    const pairing = await this.adapter.pair({ confirmationCode: code });
    const identity = validateKey(pairing.identity_public_key, 'ed25519'); const transport = validateKey(pairing.transport_public_key, 'x25519');
    if (input.identity_public_key && String(input.identity_public_key) !== identity) throw new PlatformError('pairing_transcript_mismatch', 'Bridge identity differs from the requested identity', {}, 422);
    if (input.transport_public_key && String(input.transport_public_key) !== transport) throw new PlatformError('pairing_transcript_mismatch', 'Bridge transport key differs from the requested identity', {}, 422);
    const transcriptHash = String(pairing.paired_transcript_sha256 || ''); const confirmationHash = String(pairing.confirmation_code_sha256 || '');
    if (!/^[a-f0-9]{64}$/.test(transcriptHash) || !/^[a-f0-9]{64}$/.test(confirmationHash) || !Buffer.isBuffer(pairing.secret) || pairing.secret.length !== 32) throw new PlatformError('pairing_transcript_mismatch', 'Bridge pairing result is incomplete', {}, 422);
    const id = opaqueId('bridge_device'); const secretRef = String(pairing.secretRef || `bridge-${id}`); this.vault.put(secretRef, pairing.secret);
    try {
      const result = await this.db.withTransaction((tx) => {
        const prior = priorResponse(this.operations, tx, { actorId: principal.actorId, commandId: 'bridge.pair', idempotencyKey: key, requestHash: hash, now }); if (prior) return prior;
        const op = createOperation(this.operations, tx, { actorId: principal.actorId, commandId: 'bridge.pair', resourceType: 'bridge_device', resourceId: id, requestHash: hash, status: 'succeeded', now });
        tx.run(`INSERT INTO bridge_devices(id,actor_id,label,identity_public_key,transport_public_key,shared_secret_ref,confirmation_code_sha256,paired_transcript_sha256,status,last_nonce_sequence,revision,created_at,updated_at,created_by_actor_id,updated_by_actor_id)
          VALUES(?,?,?,?,?,?,?,?, 'paired',0,1,?,?,?,?)`, [id, principal.actorId, label, identity, transport, `vault:${secretRef}`, confirmationHash, transcriptHash, now, now, principal.actorId, principal.actorId]);
        appendAggregate(this.events, tx, { aggregateType: 'bridge_device', aggregateId: id, revision: 1, operationId: op.id, actorId: principal.actorId, type: 'bridge_device.paired', data: { device_id: id, transcript_sha256: transcriptHash }, payload: { id, actor_id: principal.actorId, label, status: 'paired', revision: 1 }, now });
        this.operations.linkInTransaction(tx, op.id, [['bridge_device', id]], now); const value = { device: deviceView(tx.get('SELECT * FROM bridge_devices WHERE id=?', [id])), operation: this.operations.summary(op) };
        saveResponse(this.operations, tx, { actorId: principal.actorId, commandId: 'bridge.pair', idempotencyKey: key, requestHash: hash, response: value, operationId: op.id, status: 201, now }); return value;
      });
      if (result.replayed) { this.vault.remove(secretRef); await this.adapter.revoke({ secretRef, secret: pairing.secret }).catch(() => undefined); }
      return result;
    } catch (error) { this.vault.remove(secretRef); await this.adapter.revoke({ secretRef, secret: pairing.secret }).catch(() => undefined); throw error; }
  }

  async probe(id, input = {}, principal) {
    const row = this.deviceRow(id, principal); this.assertPaired(row); const expected = requireRevision(input.expected_revision); const key = requireIdempotency(input.idempotency_key); const commandId = 'bridge.device.probe'; const hash = requestHash({ device_id: row.id, expected_revision: expected }); const now = time(this.clock);
    const replay = await this.db.withTransaction((tx) => priorResponse(this.operations, tx, { actorId: principal.actorId, commandId, idempotencyKey: key, requestHash: hash, now })); if (replay) return replay;
    assertRevision(row, expected); const secret = this.vault.read(row.shared_secret_ref); const result = await this.adapter.probe({ secretRef: row.shared_secret_ref, secret });
    return this.db.withTransaction((tx) => { const prior = priorResponse(this.operations, tx, { actorId: principal.actorId, commandId, idempotencyKey: key, requestHash: hash, now }); if (prior) return prior; const current = tx.get('SELECT * FROM bridge_devices WHERE id=?', [row.id]); assertRevision(current, expected); const op = createOperation(this.operations, tx, { actorId: principal.actorId, commandId, resourceType: 'bridge_device', resourceId: row.id, requestHash: hash, status: 'succeeded', now }); tx.run('UPDATE bridge_devices SET last_nonce_sequence=last_nonce_sequence+1,revision=revision+1,updated_at=?,updated_by_actor_id=? WHERE id=? AND revision=?', [now, principal.actorId, row.id, expected], 1); appendAggregate(this.events, tx, { aggregateType: 'bridge_device', aggregateId: row.id, revision: expected + 1, operationId: op.id, actorId: principal.actorId, type: 'bridge_device.probed', data: { device_id: row.id, capabilities: result.capabilities || {} }, payload: { id: row.id, status: current.status, revision: expected + 1 }, now }); this.operations.linkInTransaction(tx, op.id, [['bridge_device', row.id]], now); const response = { device: deviceView(tx.get('SELECT * FROM bridge_devices WHERE id=?', [row.id])), probe: { status: result.status || 'ready', capabilities: result.capabilities || {} }, operation: this.operations.summary(op) }; saveResponse(this.operations, tx, { actorId: principal.actorId, commandId, idempotencyKey: key, requestHash: hash, response, operationId: op.id, status: 200, now }); return response; });
  }

  async rotate(id, input = {}, principal) {
    const row = this.deviceRow(id, principal); this.assertPaired(row); const expected = requireRevision(input.expected_revision); const key = requireIdempotency(input.idempotency_key); const commandId = 'bridge.device.rotate'; const hash = requestHash({ device_id: row.id, expected_revision: expected }); const now = time(this.clock);
    const replay = await this.db.withTransaction((tx) => priorResponse(this.operations, tx, { actorId: principal.actorId, commandId, idempotencyKey: key, requestHash: hash, now })); if (replay) return replay;
    assertRevision(row, expected); const old = this.vault.read(row.shared_secret_ref); const rotated = await this.adapter.rotate({ secretRef: row.shared_secret_ref, secret: old }); if (!Buffer.isBuffer(rotated.secret) || rotated.secret.length !== 32) throw new PlatformError('bridge_rotation_invalid', 'Bridge rotation result is incomplete', {}, 503); this.vault.put(String(row.shared_secret_ref).replace(/^vault:/, ''), rotated.secret);
    return this.db.withTransaction((tx) => { const prior = priorResponse(this.operations, tx, { actorId: principal.actorId, commandId, idempotencyKey: key, requestHash: hash, now }); if (prior) return prior; const current = tx.get('SELECT * FROM bridge_devices WHERE id=?', [row.id]); assertRevision(current, expected); const op = createOperation(this.operations, tx, { actorId: principal.actorId, commandId, resourceType: 'bridge_device', resourceId: row.id, requestHash: hash, status: 'succeeded', now }); tx.run('UPDATE bridge_devices SET last_nonce_sequence=0,revision=revision+1,updated_at=?,updated_by_actor_id=? WHERE id=? AND revision=?', [now, principal.actorId, row.id, expected], 1); appendAggregate(this.events, tx, { aggregateType: 'bridge_device', aggregateId: row.id, revision: expected + 1, operationId: op.id, actorId: principal.actorId, type: 'bridge_device.rotated', data: { device_id: row.id }, payload: { id: row.id, status: 'paired', revision: expected + 1 }, now }); this.operations.linkInTransaction(tx, op.id, [['bridge_device', row.id]], now); const response = { device: deviceView(tx.get('SELECT * FROM bridge_devices WHERE id=?', [row.id])), operation: this.operations.summary(op) }; saveResponse(this.operations, tx, { actorId: principal.actorId, commandId, idempotencyKey: key, requestHash: hash, response, operationId: op.id, status: 200, now }); return response; });
  }

  async revoke(id, input = {}, principal) {
    const row = this.deviceRow(id, principal); const expected = requireRevision(input.expected_revision); const key = requireIdempotency(input.idempotency_key); const commandId = 'bridge.device.revoke'; const hash = requestHash({ device_id: row.id, expected_revision: expected }); const now = time(this.clock);
    const replay = await this.db.withTransaction((tx) => priorResponse(this.operations, tx, { actorId: principal.actorId, commandId, idempotencyKey: key, requestHash: hash, now })); if (replay) return replay;
    assertRevision(row, expected); if (row.status === 'revoked') throw new PlatformError('state_conflict', 'Bridge device is already revoked', {}, 409); const secret = this.vault.read(row.shared_secret_ref); await this.adapter.revoke({ secretRef: row.shared_secret_ref, secret }).catch(() => undefined); this.vault.remove(row.shared_secret_ref);
    return this.db.withTransaction((tx) => { const prior = priorResponse(this.operations, tx, { actorId: principal.actorId, commandId, idempotencyKey: key, requestHash: hash, now }); if (prior) return prior; const current = tx.get('SELECT * FROM bridge_devices WHERE id=?', [row.id]); assertRevision(current, expected); const op = createOperation(this.operations, tx, { actorId: principal.actorId, commandId, resourceType: 'bridge_device', resourceId: row.id, requestHash: hash, status: 'succeeded', now }); tx.run("UPDATE bridge_devices SET status='revoked',revision=revision+1,updated_at=?,revoked_at=?,updated_by_actor_id=? WHERE id=? AND revision=?", [now, now, principal.actorId, row.id, expected], 1); tx.run("UPDATE bridge_transfers SET status='cancelled',revision=revision+1,updated_at=?,completed_at=? WHERE device_id=? AND status='pending'", [now, now, row.id]); appendAggregate(this.events, tx, { aggregateType: 'bridge_device', aggregateId: row.id, revision: expected + 1, operationId: op.id, actorId: principal.actorId, type: 'bridge_device.revoked', data: { device_id: row.id }, payload: { id: row.id, status: 'revoked', revision: expected + 1 }, now }); this.operations.linkInTransaction(tx, op.id, [['bridge_device', row.id]], now); const response = { device: deviceView(tx.get('SELECT * FROM bridge_devices WHERE id=?', [row.id])), operation: this.operations.summary(op) }; saveResponse(this.operations, tx, { actorId: principal.actorId, commandId, idempotencyKey: key, requestHash: hash, response, operationId: op.id, status: 200, now }); return response; });
  }

  listTransfers(id, _input = {}, principal) { const row = this.deviceRow(id, principal); return { transfers: this.db.query('SELECT * FROM bridge_transfers WHERE device_id=? ORDER BY created_at DESC,id', [row.id]).map(transferView) }; }

  async createTransfer(id, input = {}, principal) {
    const device = this.deviceRow(id, principal); this.assertPaired(device); const direction = String(input.direction || 'send'); const type = String(input.transfer_type || 'git_bundle'); if (!['send', 'receive'].includes(direction) || !['git_bundle', 'terminal_control'].includes(type)) throw new PlatformError('schema_invalid', 'Bridge transfer kind is invalid', {}, 422);
    const ref = String(input.repository_ref || ''); if (type === 'git_bundle' && ref && !/^refs\/(?:heads|tags)\/[A-Za-z0-9._/-]+$/.test(ref)) throw new PlatformError('bundle_ref_invalid', 'Git bundle ref is invalid', {}, 422);
    const head = String(input.head_sha || ''); if (head && !/^[a-f0-9]{40}(?:[a-f0-9]{24})?$/i.test(head)) throw new PlatformError('bundle_head_invalid', 'Git head SHA is invalid', {}, 422); const bundleHash = String(input.bundle_sha256 || '').toLowerCase(); if (bundleHash && !/^[a-f0-9]{64}$/.test(bundleHash)) throw new PlatformError('bundle_hash_invalid', 'Git bundle hash is invalid', {}, 422); const bytes = Number(input.byte_length || 0); if (!Number.isInteger(bytes) || bytes < 0 || bytes > 1024 * 1024 * 1024) throw new PlatformError('bundle_size_invalid', 'Git bundle size is invalid', {}, 422);
    const expected = requireRevision(input.expected_revision); const key = requireIdempotency(input.idempotency_key); const now = time(this.clock); const transferId = opaqueId('bridge_transfer'); const hash = requestHash({ device_id: device.id, expected_revision: expected, direction, transfer_type: type, repository_ref: ref, head_sha: head, bundle_sha256: bundleHash, byte_length: bytes });
    const replay = await this.db.withTransaction((tx) => priorResponse(this.operations, tx, { actorId: principal.actorId, commandId: 'bridge.transfer.create', idempotencyKey: key, requestHash: hash, now })); if (replay) return replay;
    assertRevision(device, expected); const secret = this.vault.read(device.shared_secret_ref);
    let verified; try { verified = await this.adapter.verifyBundle({ ...input, repository_ref: ref, head_sha: head, bundle_sha256: bundleHash, byte_length: bytes }, { secretRef: device.shared_secret_ref, secret }); } catch (error) { verified = { verified: false, error_code: String(error?.code || 'bundle_verify_failed') }; }
    return this.db.withTransaction((tx) => { const prior = priorResponse(this.operations, tx, { actorId: principal.actorId, commandId: 'bridge.transfer.create', idempotencyKey: key, requestHash: hash, now }); if (prior) return prior; const current = tx.get('SELECT * FROM bridge_devices WHERE id=?', [device.id]); assertRevision(current, expected); this.assertPaired(current); const status = verified.verified ? 'verified' : 'failed'; const op = createOperation(this.operations, tx, { actorId: principal.actorId, commandId: 'bridge.transfer.create', resourceType: 'bridge_transfer', resourceId: transferId, requestHash: hash, status: status === 'verified' ? 'succeeded' : 'failed', now }); tx.run('INSERT INTO bridge_transfers(id,device_id,operation_id,direction,transfer_type,repository_ref,head_sha,bundle_sha256,byte_length,status,error_code,revision,created_at,updated_at,completed_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,1,?,?,?)', [transferId, device.id, op.id, direction, type, ref, head, bundleHash, bytes, status, verified.error_code || '', now, now, now]); appendAggregate(this.events, tx, { aggregateType: 'bridge_transfer', aggregateId: transferId, revision: 1, operationId: op.id, actorId: principal.actorId, type: `bridge_transfer.${status}`, data: { transfer_id: transferId, device_id: device.id, bundle_sha256: bundleHash || undefined }, payload: { id: transferId, device_id: device.id, status, revision: 1 }, now }); this.operations.linkInTransaction(tx, op.id, [['bridge_device', device.id], ['bridge_transfer', transferId]], now); const value = { transfer: transferView(tx.get('SELECT * FROM bridge_transfers WHERE id=?', [transferId])), operation: this.operations.summary(op) }; saveResponse(this.operations, tx, { actorId: principal.actorId, commandId: 'bridge.transfer.create', idempotencyKey: key, requestHash: hash, response: value, operationId: op.id, status: status === 'verified' ? 201 : 422, now }); return value; });
  }

  deviceRow(id, principal) { requirePrincipal(principal); const row = this.db.get('SELECT * FROM bridge_devices WHERE id=? AND actor_id=?', [String(id), principal.actorId]); if (!row) throw new PlatformError('not_found', 'Bridge device not found', {}, 404); return row; }
  assertPaired(row) { if (row.status !== 'paired') throw new PlatformError('bridge_revoked', 'Bridge device is not paired', { status: row.status }, 409); if (!this.vault.has(row.shared_secret_ref)) throw new PlatformError('bridge_secret_missing', 'Bridge pairing secret is unavailable', {}, 503); }
  async recoverPending() { const rows = this.db.query("SELECT id FROM bridge_transfers WHERE status='pending'"); const now = time(this.clock); for (const row of rows) this.db.run("UPDATE bridge_transfers SET status='failed',error_code='external_result_unknown',revision=revision+1,updated_at=?,completed_at=? WHERE id=?", [now, now, row.id]); return rows.length; }
}

function validateKey(value, type) { const text = String(value || ''); try { const key = createPublicKey(text); if (key.asymmetricKeyType !== type) throw new Error('type'); return text; } catch { throw new PlatformError('bridge_key_invalid', `Bridge ${type} public key is invalid`, {}, 422); } }
function bounded(value, maximum) { const text = String(value || ''); if (!text.trim() || text.length > maximum) throw new PlatformError('schema_invalid', 'Bridge label is invalid', {}, 422); return text; }
function deviceView(row) { return { id: row.id, actor_id: row.actor_id, label: row.label, identity_public_key: row.identity_public_key, transport_public_key: row.transport_public_key, paired_transcript_sha256: row.paired_transcript_sha256, status: row.status, last_nonce_sequence: Number(row.last_nonce_sequence), revision: Number(row.revision), created_at: row.created_at, updated_at: row.updated_at, revoked_at: row.revoked_at || null }; }
function transferView(row) { return { id: row.id, device_id: row.device_id, operation_id: row.operation_id || null, direction: row.direction, transfer_type: row.transfer_type, repository_ref: row.repository_ref || null, head_sha: row.head_sha || null, bundle_sha256: row.bundle_sha256 || null, byte_length: Number(row.byte_length), status: row.status, error_code: row.error_code || null, revision: Number(row.revision), created_at: row.created_at, updated_at: row.updated_at, completed_at: row.completed_at || null }; }
