import { useCallback, useEffect, useMemo, useState } from 'react';
import { GitPullRequestDraft, LoaderCircle, Plus, RefreshCw, ShieldAlert } from 'lucide-react';
import { ApiError, apiV2, mutateV2, shortHash } from '../../api';
import type { WorkspacePageProps } from '../../workspace';
import { statusLabel } from '../../i18n';

type Policy = { id: string; name: string; status: string; revision: number; required_checks: string[] };
type Delivery = { id: string; status: string; revision: number; execution_id: string; branch_name?: string; target_head_sha?: string; error_code?: string };
type Execution = { id: string; status: string; revision: number; handoff_manifest?: { delivery_ready?: boolean } };

export function DeliveryPage({ projectId, selectedProject, notify, navigate }: WorkspacePageProps) {
  const [policies, setPolicies] = useState<Policy[]>([]); const [deliveries, setDeliveries] = useState<Delivery[]>([]); const [executions, setExecutions] = useState<Execution[]>([]);
  const [policyId, setPolicyId] = useState(''); const [executionId, setExecutionId] = useState(''); const [targetId, setTargetId] = useState(''); const [targetSha, setTargetSha] = useState('a'.repeat(40));
  const [policyName, setPolicyName] = useState('受保护的 main 分支'); const [checks, setChecks] = useState('ci'); const [busy, setBusy] = useState(''); const [error, setError] = useState('');
  const [approvalId, setApprovalId] = useState(''); const [patchSha, setPatchSha] = useState(''); const [patchCasSha, setPatchCasSha] = useState(''); const [baseSha, setBaseSha] = useState(''); const [headSha, setHeadSha] = useState('');
  const load = useCallback(async () => {
    if (!projectId) return;
    const [policy, delivery, execution, connections] = await Promise.all([
      apiV2<{ policies: Policy[] }>(`/api/v2/projects/${encodeURIComponent(projectId)}/delivery-policies`),
      apiV2<{ deliveries: Delivery[] }>(`/api/v2/deliveries?project_id=${encodeURIComponent(projectId)}`),
      apiV2<{ executions: Execution[] }>(`/api/v2/projects/${encodeURIComponent(projectId)}/executions`),
      apiV2<{ connections: Array<{ id: string }> }>(`/api/v2/projects/${encodeURIComponent(projectId)}/repository-connections`)
    ]);
    const targets = connections.data.connections[0] ? await apiV2<{ targets: Array<{ id: string; expected_head_sha?: string }> }>(`/api/v2/repository-connections/${encodeURIComponent(connections.data.connections[0].id)}/targets`) : null;
    setPolicies(policy.data.policies || []); setDeliveries(delivery.data.deliveries || []); setExecutions(execution.data.executions || []);
    setPolicyId((current) => policy.data.policies.some((row) => row.id === current) ? current : policy.data.policies[0]?.id || '');
    setExecutionId((current) => execution.data.executions.some((row) => row.id === current) ? current : execution.data.executions.find((row) => row.handoff_manifest?.delivery_ready)?.id || execution.data.executions[0]?.id || '');
    if (targets?.data.targets[0]) { setTargetId(targets.data.targets[0].id); setTargetSha(targets.data.targets[0].expected_head_sha || 'a'.repeat(40)); }
  }, [projectId]);
  useEffect(() => { void load().catch(report); }, [load]);
  const selectedExecution = useMemo(() => executions.find((row) => row.id === executionId), [executionId, executions]);
  const createPolicy = async () => run('policy', async () => { await mutateV2(`/api/v2/projects/${encodeURIComponent(projectId)}/delivery-policies`, { name: policyName, required_checks: checks.split(',').map((item) => item.trim()).filter(Boolean), approval_policy: { merge: 'owner' } }, 'POST', selectedProject?.revision ?? 0); });
  const submit = async () => run('submit', async () => { await mutateV2('/api/v2/deliveries', { execution_id: executionId, policy_id: policyId, repository_target_id: targetId, target_head_sha: targetSha }, 'POST', selectedExecution?.revision); });
  const reconcile = async (delivery: Delivery) => run(`reconcile:${delivery.id}`, async () => { await mutateV2(`/api/v2/deliveries/${encodeURIComponent(delivery.id)}/reconcile`, {}, 'POST', delivery.revision); });
  const intent = async (delivery: Delivery, action: 'create' | 'ready' | 'merge') => run(`${action}:${delivery.id}`, async () => { const body: Record<string, unknown> = { patch_sha256: patchSha, patch_cas_sha256: patchCasSha, base_sha: baseSha || delivery.target_head_sha, head_sha: headSha || delivery.target_head_sha, required_checks: checks.split(',').map((item) => item.trim()).filter(Boolean), ...(approvalId ? { approval_id: approvalId } : {}) }; if (action === 'merge') { body.expected_base_sha = body.base_sha; body.expected_head_sha = body.head_sha; } const endpoint = action === 'create' ? 'pull-request-intents' : action; await mutateV2(`/api/v2/deliveries/${encodeURIComponent(delivery.id)}/${endpoint}`, body, 'POST', delivery.revision); });
  async function run(key: string, action: () => Promise<void>) { setBusy(key); setError(''); try { await action(); await load(); notify('交付操作已接受'); } catch (caught) { report(caught); } finally { setBusy(''); } }
  function report(caught: unknown) { const message = caught instanceof ApiError ? caught.message : caught instanceof Error ? caught.message : '交付请求失败'; setError(message); notify(message, 'error'); }
  if (!projectId) return <div className="empty-state"><GitPullRequestDraft size={28} /><h2>请选择项目</h2><button className="button" onClick={() => navigate('projects')}>项目</button></div>;
  return <div className="page delivery-page-p9"><div className="page-heading"><div><p className="eyebrow">GitHub 交付</p><h1>交付</h1></div><button className="icon-button" title="刷新交付" aria-label="刷新交付" onClick={() => void load()}><RefreshCw size={16} /></button></div>
    {error && <div className="state-banner error" role="alert"><ShieldAlert size={16} /><span>{error}</span></div>}
    <div className="delivery-controls-p9"><section><div className="section-title"><div><h2>策略</h2><span>{policies.length} 个策略</span></div></div><label><span>名称</span><input value={policyName} onChange={(event) => setPolicyName(event.target.value)} /></label><label><span>必需检查</span><input value={checks} onChange={(event) => setChecks(event.target.value)} /></label><button className="button" disabled={busy === 'policy'} onClick={() => void createPolicy()}><Plus size={15} />创建策略</button></section>
      <section><div className="section-title"><div><h2>提交</h2><span>可交付交接</span></div></div><label><span>执行</span><select value={executionId} onChange={(event) => setExecutionId(event.target.value)}>{executions.map((row) => <option key={row.id} value={row.id}>{shortHash(row.id)} · {statusLabel(row.status)}</option>)}</select></label><label><span>策略</span><select value={policyId} onChange={(event) => setPolicyId(event.target.value)}>{policies.map((row) => <option key={row.id} value={row.id}>{row.name}</option>)}</select></label><button className="button primary" disabled={!executionId || !policyId || !targetId || busy === 'submit'} onClick={() => void submit()}>{busy === 'submit' ? <LoaderCircle className="spin" size={15} /> : <GitPullRequestDraft size={15} />}提交</button></section>
    </div><section className="panel delivery-intent-panel"><div className="section-title"><div><h2>交付意图链</h2><span>草稿 PR、就绪、合并和对账均为显式操作</span></div></div><div className="two-column"><label><span>审批 ID</span><input value={approvalId} onChange={(event) => setApprovalId(event.target.value)} /></label><label><span>补丁 SHA-256</span><input className="mono" value={patchSha} onChange={(event) => setPatchSha(event.target.value)} pattern="[a-fA-F0-9]{64}" /></label><label><span>补丁 CAS SHA-256</span><input className="mono" value={patchCasSha} onChange={(event) => setPatchCasSha(event.target.value)} pattern="[a-fA-F0-9]{64}" /></label><label><span>基线 SHA</span><input className="mono" value={baseSha} onChange={(event) => setBaseSha(event.target.value)} /></label><label><span>头部 SHA</span><input className="mono" value={headSha} onChange={(event) => setHeadSha(event.target.value)} /></label></div>{deliveries.map((row) => <div className="delivery-intent-row" key={row.id}><span><strong>{row.branch_name || shortHash(row.id)}</strong><small>{statusLabel(row.status)} · r{row.revision}</small></span><div className="row-actions"><button className="button" disabled={!patchSha || !patchCasSha || busy === `create:${row.id}`} onClick={() => void intent(row, 'create')}>创建草稿</button><button className="button" disabled={row.status !== 'draft_pr' || !approvalId || busy === `ready:${row.id}`} onClick={() => void intent(row, 'ready')}>标记就绪</button><button className="button primary" disabled={row.status !== 'ready' || !approvalId || busy === `merge:${row.id}`} onClick={() => void intent(row, 'merge')}>合并</button></div></div>)}</section><section className="delivery-list-p9"><div className="section-title"><div><h2>交付记录</h2><span>{deliveries.length} 条记录</span></div></div>{deliveries.map((row) => <div className="operation-row-p8" key={row.id}><span><strong>{row.branch_name || shortHash(row.id)}</strong><small>{row.status === 'needs_reconcile' ? '外部结果未知' : shortHash(row.target_head_sha || row.execution_id)}</small></span><div className="operation-row-tail-p8"><Status value={row.status} />{row.status === 'needs_reconcile' && <button className="button" disabled={busy === `reconcile:${row.id}`} onClick={() => void reconcile(row)}>对账</button>}</div></div>)}{!deliveries.length && <p className="list-empty">暂无交付记录</p>}</section>
  </div>;
}
function Status({ value }: { value: string }) { const tone = ['merged', 'ready', 'draft_pr'].includes(value) ? 'positive' : ['queued', 'running'].includes(value) ? 'working' : ['failed', 'needs_reconcile'].includes(value) ? 'negative' : 'neutral'; return <span className={`status ${tone}`}><span />{statusLabel(value)}</span>; }
