import assert from 'node:assert/strict';
import { generateKeyPairSync } from 'node:crypto';
import test from 'node:test';
import { DeterministicRunnerAdapter } from '../../apps/api/src/clean/runner-adapters.mjs';
import { signRunnerJobSpec, signRunnerReceipt, validateRunnerJobSpec, verifyRunnerReceipt } from '../../apps/api/src/clean/runner-protocol.mjs';
import { close, open, prepare, waitOperation } from './helpers.mjs';

test('runner protocol rejects path, deadline, digest, capability and receipt tampering', () => {
  const key = generateKeyPairSync('ed25519'); const now = Date.now(); const spec = { schema_version: 'runner.job-spec.v2', job_spec_id: 'job_fixture', execution_ref: 'execution_fixture', generation: 1, task_ref: 'task_fixture', attempt: 1, runner_profile_ref: 'runner_fixture', runner_profile_revision: 1, runner_profile_hash: 'a'.repeat(64), image_digest: `sha256:${'b'.repeat(64)}`, deadline_at: new Date(now + 60_000).toISOString(), capabilities: ['network:none', 'workspace:read'], resource_profile: 'light', execution_mode: 'read', input_refs: [], input_paths: ['README.md'], output_paths: [], check_ids: [], workspace_ref: 'workspace_fixture', workspace_hash: 'c'.repeat(64), context_pack_ref: 'context_fixture', context_pack_hash: 'd'.repeat(64), service_key_id: 'runner_key_fixture', created_at: new Date(now).toISOString() };
  const signed = signRunnerJobSpec(spec, key.privateKey, { now }); assert.equal(signed.spec_sha256.length, 64);
  assert.throws(() => validateRunnerJobSpec({ ...spec, input_paths: ['C:\\secret'] }, { now }), (error) => error.code === 'runner_path_invalid');
  assert.throws(() => validateRunnerJobSpec({ ...spec, deadline_at: new Date(now + 16 * 60_000).toISOString() }, { now }), (error) => error.code === 'runner_deadline_invalid');
  assert.throws(() => validateRunnerJobSpec({ ...spec, capabilities: ['docker:socket'] }, { now }), (error) => error.code === 'runner_capability_denied');
  const receipt = { schema_version: 'runner.receipt.v2', receipt_id: 'receipt_fixture', job_spec_id: spec.job_spec_id, job_spec_hash: signed.spec_sha256, runner_profile_ref: spec.runner_profile_ref, runner_job_ref: 'runner_job_fixture', status: 'succeeded', exit_code: 0, stdout_sha256: '', stderr_sha256: '', output_sha256: '', stdout_bytes: 0, stderr_bytes: 0, output_bytes: 0, output_paths: [], error_code: '', started_at: new Date(now).toISOString(), finished_at: new Date(now + 1).toISOString() };
  const signedReceipt = signRunnerReceipt(receipt, key.privateKey); assert.equal(verifyRunnerReceipt(receipt, signedReceipt.signature, key.publicKey, { expectedJobSpecId: spec.job_spec_id, expectedJobSpecHash: signed.spec_sha256 }).receipt.status, 'succeeded'); assert.throws(() => verifyRunnerReceipt({ ...receipt, exit_code: 1 }, signedReceipt.signature, key.publicKey), (error) => error.code === 'runner_receipt_signature_invalid');
});

test('P6 completes stable seven-stage execution with read concurrency, write serialization and immutable receipts', async () => {
  let activeReads = 0; let activeWrites = 0; let maxReads = 0; let overlappingWrite = false;
  const adapter = new DeterministicRunnerAdapter({ execute: async (spec) => { if (spec.execution_mode === 'read') { activeReads += 1; maxReads = Math.max(maxReads, activeReads); if (activeWrites) overlappingWrite = true; await new Promise((resolve) => setTimeout(resolve, 15)); activeReads -= 1; } else { activeWrites += 1; if (activeReads || activeWrites > 1) overlappingWrite = true; await new Promise((resolve) => setTimeout(resolve, 5)); activeWrites -= 1; } return { status: 'succeeded', exit_code: 0, stdout: Buffer.from('ok\n') }; } });
  const state = await open({ adapter });
  try { const tasks = [{ id: 'read_a', mode: 'read', depends_on: [], input_paths: ['README.md'], output_paths: [] }, { id: 'read_b', mode: 'read', depends_on: [], input_paths: ['README.md'], output_paths: [] }, { id: 'write', mode: 'write', depends_on: ['read_a', 'read_b'], input_paths: ['README.md'], output_paths: [] }]; const fixture = await prepare(state, 'complete', tasks); const started = await state.runtime.execution.start(fixture.execution.id, { expected_revision: fixture.execution.revision, idempotency_key: 'p6-complete-start' }, state.principal); const operation = await waitOperation(state.runtime, started.operation.operation_id, state.principal.actorId); assert.equal(operation.status, 'succeeded'); const execution = state.runtime.execution.get(fixture.execution.id, state.principal); assert.equal(execution.status, 'completed'); assert.equal(execution.current_stage, 'deliver'); assert.equal(execution.handoff_manifest.delivery_ready, true); assert.equal(maxReads, 2); assert.equal(overlappingWrite, false); assert.equal(state.runtime.execution.checkpointsFor(execution.id, {}, state.principal).checkpoints.length, 7); assert.equal(state.runtime.execution.attemptsFor(execution.id, {}, state.principal).attempts.length, 3); assert.equal(state.runtime.db.get('SELECT count(*) AS count FROM runner_receipts').count, 3); assert.equal(state.runtime.db.get('SELECT count(*) AS count FROM execution_events').count, state.runtime.db.get("SELECT count(*) AS count FROM events WHERE aggregate_type='execution'").count); assert.throws(() => state.runtime.db.run("UPDATE runner_receipts SET status='failed'"), /immutable_runner_receipt/); assert.throws(() => state.runtime.db.run("UPDATE execution_stage_checkpoints SET stage='prepare'"), /immutable_execution_checkpoint/); assert.equal(state.runtime.db.integrity().semantic.valid, true); } finally { await close(state); }
});

test('execution rejects DAG cycles and stale checkpoint replay inputs', async () => {
  const state = await open();
  try { const base = await prepare(state, 'replay'); const project = state.runtime.db.get('SELECT * FROM projects WHERE id=?', [base.project.id]); await assert.rejects(() => state.runtime.execution.create(base.project.id, { repository_workspace_id: base.workspace.id, context_pack_id: base.pack.id, runner_profile_id: base.profile.id, tasks: [{ id: 'a', depends_on: ['b'] }, { id: 'b', depends_on: ['a'] }], expected_revision: project.revision, idempotency_key: 'p6-cycle-create' }, state.principal), (error) => error.code === 'execution_dag_cycle'); const started = await state.runtime.execution.start(base.execution.id, { expected_revision: base.execution.revision, idempotency_key: 'p6-replay-start' }, state.principal); await waitOperation(state.runtime, started.operation.operation_id, state.principal.actorId); const finished = state.runtime.execution.get(base.execution.id, state.principal); const checkpoint = state.runtime.execution.checkpointsFor(finished.id, {}, state.principal).checkpoints.find((item) => item.stage === 'deliver'); await assert.rejects(() => state.runtime.execution.replayStage(finished.id, 'deliver', { generation: finished.generation, checkpoint_token: 'x'.repeat(43), expected_revision: finished.revision, idempotency_key: 'p6-replay-bad-token' }, state.principal), (error) => error.code === 'checkpoint_token_invalid'); } finally { await close(state); }
});
