import { useCallback, useEffect, useState } from 'react';
import { Archive, FileText, LoaderCircle, Plus, RefreshCw, Save } from 'lucide-react';
import { apiV2, mutateV2 } from '../../api';
import { statusLabel } from '../../i18n';

type Template = { id: string; name: string; description?: string; status: string; current_revision: number; revision: number; content: Record<string, unknown> };

export function BriefTemplatesPanel({ notify }: { notify: (text: string, tone?: 'ok' | 'error') => void }) {
  const [templates, setTemplates] = useState<Template[]>([]); const [name, setName] = useState(''); const [description, setDescription] = useState(''); const [content, setContent] = useState('{"objective":"","acceptance":[]}'); const [busy, setBusy] = useState(''); const [error, setError] = useState('');
  const load = useCallback(async () => { try { const result = await apiV2<{ templates: Template[] }>('/api/v2/brief-templates?include_archived=true'); setTemplates(result.data.templates || []); setError(''); } catch (caught) { setError(caught instanceof Error ? caught.message : '模板请求失败'); } }, []);
  useEffect(() => { void load(); }, [load]);
  const create = async () => { let parsed: Record<string, unknown>; try { parsed = JSON.parse(content); } catch { setError('模板内容必须是有效 JSON'); return; } setBusy('create'); try { await mutateV2('/api/v2/brief-templates', { name: name.trim(), description: description.trim(), content: parsed }, 'POST', 0); setName(''); setDescription(''); await load(); notify('Brief 模板已创建'); } catch (caught) { setError(caught instanceof Error ? caught.message : '模板创建失败'); } finally { setBusy(''); } };
  const archive = async (template: Template) => { setBusy(template.id); try { await mutateV2(`/api/v2/brief-templates/${encodeURIComponent(template.id)}/archive`, {}, 'POST', template.revision); await load(); notify('Brief 模板已归档'); } catch (caught) { setError(caught instanceof Error ? caught.message : '模板归档失败'); } finally { setBusy(''); } };
  return <section className="panel brief-templates-panel"><div className="section-title"><div><h2>Brief 模板</h2><span>{templates.length} 个不可变模板</span></div><button className="icon-button" aria-label="刷新模板" title="刷新" onClick={() => void load()} disabled={Boolean(busy)}><RefreshCw className={busy === 'load' ? 'spin' : ''} size={15} /></button></div>{error && <div className="state-banner error" role="alert">{error}</div>}<div className="compact-list">{templates.map((template) => <div className="compact-row" key={template.id}><span><strong>{template.name}</strong><small>{template.description || '暂无说明'} · r{template.current_revision}</small></span><span className={`status ${template.status === 'active' ? 'positive' : 'negative'}`}><span />{statusLabel(template.status)}</span>{template.status !== 'archived' && <button className="icon-button" aria-label={`归档模板 ${template.name}`} title="归档" disabled={busy === template.id} onClick={() => void archive(template)}><Archive size={14} /></button>}</div>)}{!templates.length && <div className="list-empty">暂无模板</div>}</div><div className="template-create-form"><label><span>名称</span><input value={name} onChange={(event) => setName(event.target.value)} placeholder="交付 Brief" /></label><label><span>说明</span><input value={description} onChange={(event) => setDescription(event.target.value)} /></label><label><span>内容 JSON</span><textarea rows={5} value={content} onChange={(event) => setContent(event.target.value)} /></label><button className="button primary" disabled={!name.trim() || busy === 'create'} onClick={() => void create()}>{busy === 'create' ? <LoaderCircle className="spin" size={15} /> : <Plus size={15} />}创建模板</button></div></section>;
}
