param([switch]$DryRun,[switch]$Apply,[string]$IsolatedRoot,[string]$SourceRoot)
$ErrorActionPreference='Stop'
if (($DryRun -and $Apply) -or (-not $DryRun -and -not $Apply)) { throw 'choose_exactly_one_mode' }
$Evidence=(Resolve-Path $PSScriptRoot).Path
if ([string]::IsNullOrWhiteSpace($SourceRoot)) { $SourceRoot=$Evidence; while ($SourceRoot -and -not (Test-Path (Join-Path $SourceRoot '.git'))) { $Parent=Split-Path -Parent $SourceRoot; if ($Parent -eq $SourceRoot) { $SourceRoot=$null } else { $SourceRoot=$Parent } }; if (-not $SourceRoot) { throw 'rollback_repo_root_missing' } }
$SourceRoot=[IO.Path]::GetFullPath($SourceRoot); $Patch=Join-Path $Evidence 'change.patch'; $Original=Get-Content (Join-Path $Evidence 'original-hashes.json') -Raw | ConvertFrom-Json; $Modified=Get-Content (Join-Path $Evidence 'modified-artifact.json') -Raw | ConvertFrom-Json; $Snapshot=Join-Path $Evidence 'rollback-v5.sqlite'; $ComponentsFile=Join-Path $Evidence 'rollback-components-v5.json'; $SnapshotMeta=Get-Content (Join-Path $Evidence 'rollback-snapshot.json') -Raw | ConvertFrom-Json; $Components=Get-Content $ComponentsFile -Raw | ConvertFrom-Json
function Get-FileSha256([string]$Path) { return (Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash.ToLowerInvariant() }
function Get-BytesSha256([byte[]]$Bytes) { $Hasher=[Security.Cryptography.SHA256]::Create(); try { return ([Convert]::ToHexString($Hasher.ComputeHash($Bytes))).ToLowerInvariant() } finally { $Hasher.Dispose() } }
function Resolve-Child([string]$Base,[string]$Relative) { if ([IO.Path]::IsPathRooted($Relative) -or (($Relative -split '[\\/]') -contains '..')) { throw 'rollback_relative_path_invalid' }; $BaseFull=[IO.Path]::GetFullPath($Base); $Target=[IO.Path]::GetFullPath((Join-Path $BaseFull $Relative)); $Prefix=$BaseFull.TrimEnd([IO.Path]::DirectorySeparatorChar,[IO.Path]::AltDirectorySeparatorChar)+[IO.Path]::DirectorySeparatorChar; if (-not $Target.StartsWith($Prefix,[StringComparison]::OrdinalIgnoreCase)) { throw 'rollback_relative_path_invalid' }; return $Target }
$Mismatches=[Collections.Generic.List[string]]::new()
if ((Get-FileSha256 $Snapshot) -ne [string]$SnapshotMeta.database.sha256) { $Mismatches.Add('snapshot:sqlite') }
if ((Get-FileSha256 $ComponentsFile) -ne [string]$SnapshotMeta.components.sha256) { $Mismatches.Add('snapshot:components') }
foreach ($Property in $Components.components.PSObject.Properties) { foreach ($File in @($Property.Value.files)) { $Payload=[Convert]::FromBase64String([string]$File.base64); if ($Payload.Length -ne [int]$File.bytes -or (Get-BytesSha256 $Payload) -ne [string]$File.sha256) { $Mismatches.Add(('snapshot:'+ $Property.Name + ':' + [string]$File.path)) } } }
& git -C $SourceRoot -c core.autocrlf=false apply --reverse --check $Patch; if ($LASTEXITCODE -ne 0) { throw 'rollback_source_reverse_check_failed' }
if ($DryRun) { $MismatchJson=if ($Mismatches.Count -eq 0) { '[]' } else { @($Mismatches)|ConvertTo-Json -Compress }; Write-Output 'rollback_mode=dry-run'; Write-Output 'source_reverse_check=passed'; Write-Output ('byte_exact_mismatches='+$MismatchJson); if ($Mismatches.Count -ne 0) { throw 'rollback_snapshot_mismatch' }; exit 0 }
if ([string]::IsNullOrWhiteSpace($IsolatedRoot)) { $IsolatedRoot=Join-Path $env:TEMP ('aiws-p6-rollback-'+[guid]::NewGuid().ToString('N')) }
$IsolatedRoot=[IO.Path]::GetFullPath($IsolatedRoot); if ($IsolatedRoot -eq $SourceRoot -or $IsolatedRoot -eq $Evidence) { throw 'rollback_isolated_root_invalid' }; if ((Test-Path -LiteralPath $IsolatedRoot) -and (@(Get-ChildItem -LiteralPath $IsolatedRoot -Force).Count -gt 0)) { throw 'rollback_isolated_root_not_empty' }; New-Item -ItemType Directory -Path $IsolatedRoot -Force | Out-Null
& git -C $SourceRoot -c core.autocrlf=false apply --reverse --whitespace=nowarn $Patch; if ($LASTEXITCODE -ne 0) { throw 'rollback_source_apply_failed' }
$OriginalMap=@{}; foreach ($Entry in @($Original.files)) { $OriginalMap[[string]$Entry.path]=$Entry }; foreach ($Relative in @($Modified.changed_files)) { $Target=Resolve-Child $SourceRoot ([string]$Relative); if ($OriginalMap.ContainsKey([string]$Relative)) { if (-not (Test-Path -LiteralPath $Target -PathType Leaf) -or (Get-FileSha256 $Target) -ne [string]$OriginalMap[[string]$Relative].sha256) { $Mismatches.Add(('source:'+ [string]$Relative)) } } elseif (Test-Path -LiteralPath $Target) { $Mismatches.Add(('source_orphan:'+ [string]$Relative)) } }
$Data=Join-Path $IsolatedRoot 'data'; New-Item -ItemType Directory -Path $Data -Force | Out-Null; $DatabaseTarget=Join-Path $Data 'state.sqlite'; Copy-Item $Snapshot $DatabaseTarget
$Restored=[ordered]@{sqlite=$false;cas=$false;vault=$false;workspace=$false;broker=$false;bridge=$false}; $Restored.sqlite=((Get-FileSha256 $DatabaseTarget) -eq [string]$SnapshotMeta.database.sha256)
foreach ($Property in $Components.components.PSObject.Properties) { $Name=$Property.Name; $Component=$Property.Value; $ComponentRoot=Resolve-Child $IsolatedRoot ([string]$Component.root); New-Item -ItemType Directory -Path $ComponentRoot -Force | Out-Null; $ComponentOk=$true; foreach ($File in @($Component.files)) { $Target=Resolve-Child $ComponentRoot ([string]$File.path); New-Item -ItemType Directory -Path (Split-Path -Parent $Target) -Force | Out-Null; $Payload=[Convert]::FromBase64String([string]$File.base64); [IO.File]::WriteAllBytes($Target,$Payload); if ((Get-FileSha256 $Target) -ne [string]$File.sha256) { $Mismatches.Add(('component:'+ $Name + ':' + [string]$File.path)); $ComponentOk=$false } }; $Restored[$Name]=$ComponentOk }
$Probe=@'
const {DatabaseSync}=require("node:sqlite");
const db=new DatabaseSync(process.argv[2],{readOnly:true});
const n=v=>Object.fromEntries(Object.entries(v).map(([k,x])=>[k,typeof x==='bigint'?Number(x):x]));
const p6=['execution_events','execution_inputs','execution_stage_checkpoints','executions','job_specs','runner_profiles','runner_receipts','task_attempts'];
const present=new Set(db.prepare("SELECT name FROM sqlite_schema WHERE type='table'").all().map(x=>x.name));
const r={user_version:Number(db.prepare("PRAGMA user_version").get().user_version),foreign_key_check:db.prepare("PRAGMA foreign_key_check").all().map(n),migration_ledger:db.prepare("SELECT version FROM schema_migrations ORDER BY version").all().map(n),p6_tables_absent:p6.filter(x=>!present.has(x))};
db.close(); process.stdout.write(JSON.stringify(r));
'@
$ProbeJson=$Probe | & node - $DatabaseTarget; if ($LASTEXITCODE -ne 0) { throw 'rollback_database_probe_failed' }; $Db=$ProbeJson | ConvertFrom-Json; if ([int]$Db.user_version -ne 5) { $Mismatches.Add('user_version') }; if (@($Db.foreign_key_check).Count -ne 0) { $Mismatches.Add('foreign_key_check') }; $Ledger=@($Db.migration_ledger | % {[int]$_.version}); if (($Ledger -join ',') -ne '1,2,3,4,5') { $Mismatches.Add('migration_ledger') }; if ((@($Db.p6_tables_absent) -join ',') -ne 'execution_events,execution_inputs,execution_stage_checkpoints,executions,job_specs,runner_profiles,runner_receipts,task_attempts') { $Mismatches.Add('p6_tables_absent') }; foreach ($Role in @('sqlite','cas','vault','workspace','broker','bridge')) { if ($Restored[$Role] -ne $true) { $Mismatches.Add(('restored_component:'+ $Role)) } }
$ForeignKeyJson=if (@($Db.foreign_key_check).Count -eq 0) { '[]' } else { @($Db.foreign_key_check)|ConvertTo-Json -Compress }; $MismatchJson=if ($Mismatches.Count -eq 0) { '[]' } else { @($Mismatches)|ConvertTo-Json -Compress }; $LedgerJson=@($Ledger)|ConvertTo-Json -Compress; $P6AbsentJson=@($Db.p6_tables_absent)|ConvertTo-Json -Compress; $RestoredJson=$Restored|ConvertTo-Json -Compress
Write-Output 'rollback_mode=apply'; Write-Output 'source_reverse_check=passed'; Write-Output ('user_version='+[int]$Db.user_version); Write-Output ('foreign_key_check='+$ForeignKeyJson); Write-Output ('migration_ledger='+$LedgerJson); Write-Output ('p6_tables_absent='+$P6AbsentJson); Write-Output ('restored_components='+$RestoredJson); Write-Output ('byte_exact_mismatches='+$MismatchJson); if ($Mismatches.Count -ne 0) { throw 'rollback_byte_exact_mismatch' }