import { HttpError, command, makeRoute, send } from '../http.mjs';
import { ROOT } from '../config.mjs';
import { addTrace, mutate, owner, readState } from '../state.mjs';
import { ToolType, createTool, maskSecretsDeep, pick, now } from '../../../../packages/shared/index.mjs';

export const toolRoutes = [
  makeRoute('GET', '/tools', async ({ res }) => send(res, 200, (await readState()).tools)),
  makeRoute('POST', '/tools', async ({ res, body }) => { const result = await mutate((state) => { const actor = owner(state); const tool = createTool({ ...body, type: body.type || ToolType.Cli, created_by_user_id: actor.id }); state.tools.push(tool); addTrace(state, 'human.reviewed', { target_type: 'tool', target_id: tool.id, summary: `创建工具：${tool.name}` }, actor.id); return tool; }); return send(res, 201, result); }),
  makeRoute('PUT', '/tools/:id', async ({ res, params, body }) => { const result = await mutate((state) => { const tool = state.tools.find((t) => t.id === params.id); if (!tool) throw new HttpError(404, 'tool_not_found'); Object.assign(tool, maskSecretsDeep(pick(body, ['name', 'type', 'description', 'config', 'enabled', 'capabilities', 'permissions', 'usage_boundary']))); tool.updated_at = now(); return tool; }); return send(res, 200, result); }),
  makeRoute('POST', '/tools/:id/health', async ({ res, params }) => { const result = await mutate((state) => { const actor = owner(state); const tool = state.tools.find((t) => t.id === params.id); if (!tool) throw new HttpError(404, 'tool_not_found'); let status = { ok: true, stdout: 'built-in ok', stderr: '' }; if (tool.type === ToolType.Cli) status = command(tool.config?.command || tool.name, tool.config?.health_args || ['--version'], ROOT, 5000); else if (tool.type === ToolType.McpHttp || tool.type === ToolType.Api) status = { ok: true, stdout: `mock health ok for ${tool.config?.url || tool.name}`, stderr: '' }; else if (tool.type === ToolType.McpStdio) { status = { ok: true, stdout: 'mock stdio MCP initialize/tools/list ok', stderr: '' }; tool.discovered_tools = [{ name: `${tool.name}.echo`, description: 'mock discovered tool' }]; } else if (tool.type === ToolType.DockerCompose) status = command('docker', ['compose', 'version'], ROOT, 5000); Object.assign(tool, { health_status: status.ok ? 'healthy' : 'unhealthy', health_log: `${status.stdout}\n${status.stderr || status.error || ''}`.trim(), last_checked_at: now(), updated_at: now() }); addTrace(state, 'tool.health.checked', { target_type: 'tool', target_id: tool.id, summary: `工具健康检查：${tool.name} → ${tool.health_status}`, data: status }, actor.id); return tool; }); return send(res, 200, result); })
];
