import { AssetStatus, NodeType } from './enums.mjs';
import { defaultContractForNode } from './domain.mjs';
import { generatePrBody } from './context-run.mjs';
import { id, now, pick, unique } from './utils.mjs';

export function buildAssistResult({ state, target_type, target_id, user_prompt = '', project, node, contract, asset, digest, diff }) {
  const base = { id: id('astres'), status: 'draft_ready', summary: '', questions: [], options: [], assumptions: [], draft_patch: {}, next_actions: [], created_at: now() };
  if (target_type === 'project_wizard') return projectWizardAssist(base, project, user_prompt);
  if (target_type === 'node_contract') return nodeContractAssist(base, project, node, contract);
  if (target_type === 'context_pack_preview') return contextPackAssist(base, state, target_id);
  if (target_type === 'asset_review') return assetReviewAssist(base, asset);
  if (target_type === 'digest') return digestAssist(base, digest);
  if (target_type === 'git_review') return gitReviewAssist(base, project, node, target_id, diff);
  return { ...base, status: 'needs_user_choice', summary: '当前目标需要更多上下文。', questions: [{ id: id('q'), question: '你希望 Codex 帮你生成什么草稿？', why: 'Assist 不会直接写入系统事实。', required: true }], options: [{ id: id('opt'), label: '生成草稿', description: '创建可编辑 draft_patch。', impact: '需用户确认后写入。', recommended: true }, { id: id('opt'), label: '只列问题', description: '不改任何字段。', impact: '适合探索。', recommended: false }] };
}
function projectWizardAssist(base, project, user_prompt) {
  const unclear = !project?.goal || String(project.goal).length < 12 || /模糊|随便|不知道|帮我/.test(user_prompt || project.goal || '');
  return { ...base, status: unclear ? 'needs_user_choice' : 'draft_ready', summary: unclear ? '项目目标仍偏模糊，建议先选择一个可演示闭环任务。' : '项目目标足够进入工作流推荐。', questions: unclear ? [{ id: id('q'), question: '你希望这次演示优先证明哪类能力？', why: '这会决定节点契约和验收标准。', required: true }] : [], options: [{ id: id('opt'), label: 'Tool Registry CRUD', description: '实现工具注册、健康检查和 Context Pack 注入。', impact: '覆盖开发计划 M6，适合毕业设计演示。', recommended: true }, { id: id('opt'), label: '文档修改任务', description: '让 Codex 修改 README 并形成 Trace/Asset/Digest/Git。', impact: '最快跑通闭环。', recommended: false }, { id: id('opt'), label: 'Context Pack 优化', description: '强化 Memory Manifest、pin/unpin 和质量自检。', impact: '突出系统核心差异化。', recommended: false }], assumptions: ['V1 以本地单用户 Local Owner 为主。', 'GitHub 绑定可选，未绑定时生成 PR 草稿。'], draft_patch: { title: project?.title || 'AI Workspace System 自身功能开发', goal: project?.goal || '实现 Tool Registry 基础 CRUD，并跑通 Context Pack、Trace、Asset、Digest、Git Review 闭环。', role: project?.role || '面向毕业设计演示的本地优先 AI 协作工作空间开发者', background: project?.background || '系统需要证明 Codex 能在可追溯、可接续、可资产化的工作空间中完成任务。' }, next_actions: ['应用推荐草稿', '生成 5 节点工作流', '确认执行节点契约'] };
}
function nodeContractAssist(base, project, node, contract) {
  const draft = contract || defaultContractForNode(node || { id: 'node', title: '节点', goal: '', type: NodeType.Execution }, project || { goal: '' }, 'system');
  return { ...base, status: 'needs_user_choice', summary: `已为「${node?.title || '当前节点'}」生成可选择的 Node Contract 草稿。`, questions: [{ id: id('q'), question: '该节点是否需要允许 Codex 修改本地 repo 文件？', why: '会影响 allowed_tools 和 Git Review。', required: node?.type === NodeType.Execution }, { id: id('q'), question: '哪些输出必须由用户确认后才能进入长期记忆？', why: '避免 AI 输出污染资产库。', required: true }], options: [{ id: id('opt'), label: '严格工程闭环', description: '要求测试、diff、资产候选、Digest、commit 全部可追溯。', impact: '最符合 V1 Definition of Done。', recommended: true }, { id: id('opt'), label: '快速演示闭环', description: '优先 MockRunner，保留 Codex live 可选。', impact: '更稳定，适合现场演示。', recommended: false }, { id: id('opt'), label: '研究型节点', description: '强调资料证据、引用和结论资产。', impact: '适合调研/分析节点。', recommended: false }], draft_patch: { node_goal: draft.node_goal || node?.goal || '', acceptance_criteria: ['Context Pack 质量自检全部通过，且 Memory Manifest 可解释纳入/排除原因。', 'Runner 输出必须生成 Trace，并保存 raw output。', '资产只能以 candidate 形式生成，用户确认后才进入 confirmed Asset。', '若涉及代码变更，必须展示 diff、测试结果和 commit/PR 草稿。'], allowed_tools: unique([...(draft.allowed_tools || []), 'filesystem', 'git', 'mock_runner']), failure_policy: { on_missing_context: 'assist_ask_minimal_questions', on_conflict: 'block_certainty_and_request_user_choice', on_runner_error: 'record_trace_keep_raw_log_offer_retry' }, review_policy: { human_required: true, required_reviews: ['context_pack', 'asset_candidate', 'digest', 'git_commit'] } }, next_actions: ['应用到 Node Contract 草稿', '确认 Contract', '生成 Context Pack Preview'] };
}
function contextPackAssist(base, state, target_id) { const ctx = state.context_packs.find((c) => c.id === target_id); const warnings = ctx?.quality_check?.warnings || []; return { ...base, status: warnings.length ? 'needs_user_choice' : 'draft_ready', summary: warnings.length ? `Context Pack 有 ${warnings.length} 个需要关注的问题。` : 'Context Pack 已满足运行前质量要求。', questions: warnings.map((w) => ({ id: id('q'), question: `是否处理：${w}？`, why: '降低 Codex 基于旧/冲突记忆执行的风险。', required: false })), options: [{ id: id('opt'), label: '保留并标记风险', description: '继续运行，但把风险写入 Runner Instruction。', impact: '不中断流程。', recommended: warnings.length === 0 }, { id: id('opt'), label: '回到契约补全', description: '先修复缺失字段或冲突记忆。', impact: '更稳妥。', recommended: warnings.length > 0 }], draft_patch: { pinned_refs: ctx?.memory_manifest?.included?.slice(0, 3).map((m) => m.ref) || [] }, next_actions: ['确认 Context Pack', '或回到 Contract/Asset 修正'] }; }
function assetReviewAssist(base, asset) { return { ...base, status: 'needs_user_choice', summary: `资产候选「${asset?.title || '未命名资产'}」建议先检查证据完整性。`, questions: asset?.evidence_refs?.length ? [] : [{ id: id('q'), question: '该资产的证据来源是什么？', why: 'confirmed Asset 必须有 evidence_refs。', required: true }], options: [{ id: id('opt'), label: '确认资产', description: '证据充分，进入下次 Context Pack。', impact: '成为系统长期记忆。', recommended: Boolean(asset?.evidence_refs?.length) }, { id: id('opt'), label: '编辑后确认', description: '先补充标题、摘要或证据。', impact: '提高可追溯性。', recommended: !asset?.evidence_refs?.length }, { id: id('opt'), label: '拒绝资产', description: '保留 Trace，但不进入 Context Pack。', impact: '避免记忆污染。', recommended: false }], draft_patch: { title: asset?.title || '待确认资产', summary: asset?.summary || '请补充该资产的价值、证据和适用范围。', tags: unique([...(asset?.tags || []), 'reviewed']) }, next_actions: ['确认 / 编辑 / 拒绝资产候选'] }; }
function digestAssist(base, digest) { return { ...base, status: 'draft_ready', summary: '已生成 Digest 草稿，用于下一次 Context Pack 接续。', options: [{ id: id('opt'), label: '确认 Digest', description: '作为当前工作区最新摘要。', impact: '下次 Context Pack 默认引用。', recommended: true }, { id: id('opt'), label: '补充未决问题', description: '把 open questions 写入 Digest。', impact: '降低后续歧义。', recommended: false }], draft_patch: { summary: digest?.summary || '本轮已完成节点运行、资产候选 Review 和 Git/Trace 记录。', open_questions: digest?.open_questions || ['是否需要真实 Codex live run？', '是否绑定 GitHub 创建 PR？'] }, next_actions: ['确认 Digest', '进入下一个节点'] }; }
function gitReviewAssist(base, project, node, target_id, diff) { return { ...base, status: 'draft_ready', summary: '已根据 diff / test results 生成 commit message 和 PR body 草稿。', options: [{ id: id('opt'), label: '提交选中文件', description: '生成本地 commit。', impact: '形成 CodeChangeAsset 候选。', recommended: true }, { id: id('opt'), label: '仅生成 PR 草稿', description: '不 push，不调用 GitHub。', impact: '适合未绑定 GitHub。', recommended: false }], draft_patch: { commit_message: `feat(aiws): ${node?.title || 'complete node run'}\n\n- NodeRun: ${target_id || ''}\n- Tests: ${diff?.tests_status || 'not run'}`, pr_body: generatePrBody({ project, node, run: { id: target_id }, diff }) }, next_actions: ['选择文件', '运行测试', '确认 commit 或 PR 草稿'] }; }

export function makeAssetFromCandidate(candidate, { projectId, workspaceId, nodeId, runId, actorId, status = AssetStatus.Candidate }) { const assetId = id('ast'), versionId = id('av'), created = now(); return { asset: { id: assetId, project_id: projectId, workspace_id: workspaceId, node_id: nodeId, run_id: runId, asset_type: candidate.asset_type || 'DecisionAsset', title: candidate.title || '未命名资产候选', summary: candidate.summary || '', status, scope: 'project', evidence_refs: candidate.evidence_refs || [`node_run:${runId}`], tags: candidate.tags || [], current_version_id: versionId, created_by_user_id: actorId, confirmed_by_user_id: status === AssetStatus.Confirmed ? actorId : null, created_at: created, updated_at: created }, version: { id: versionId, asset_id: assetId, version: 1, title: candidate.title || '未命名资产候选', summary: candidate.summary || '', body: candidate.body || candidate.summary || '', evidence_refs: candidate.evidence_refs || [`node_run:${runId}`], confirmed_by_user_id: status === AssetStatus.Confirmed ? actorId : null, created_at: created } }; }
export function confirmAsset(asset, version, actorId, patch = {}) { if (!Array.isArray(asset.evidence_refs) || asset.evidence_refs.length === 0) throw new Error('confirmed Asset 必须有 evidence_refs'); const next = { ...asset, ...pick(patch, ['title', 'summary', 'tags']), status: AssetStatus.Confirmed, confirmed_by_user_id: actorId, updated_at: now() }; const newVersion = { ...version, id: id('av'), asset_id: asset.id, version: Number(version.version || 1) + 1, title: next.title, summary: next.summary, body: patch.body || version.body || next.summary, evidence_refs: next.evidence_refs, confirmed_by_user_id: actorId, created_at: now() }; next.current_version_id = newVersion.id; return { asset: next, version: newVersion }; }
export function buildDigest({ state, project, workspace, actorId, summaryPatch = {} }) { const previous = state.digests.filter((d) => d.workspace_id === workspace.id).sort((a, b) => a.version - b.version).at(-1); const assets = state.assets.filter((a) => (a.workspace_id === workspace.id || a.project_id === project.id) && a.status === AssetStatus.Confirmed); const runs = state.node_runs.filter((r) => r.workspace_id === workspace.id || r.project_id === project.id).slice(-5); const version = (previous?.version || 0) + 1; const summary = summaryPatch.summary || `Digest v${version}: 已确认 ${assets.length} 个资产，最近 ${runs.length} 次 NodeRun 可追溯。`; const body = [summary, '', '## Confirmed Assets', ...assets.slice(-8).map((a) => `- ${a.title}: ${a.summary}`), '', '## Recent Runs', ...runs.map((r) => `- ${r.id}: ${r.status} · ${r.summary || ''}`), '', '## Open Questions', ...((summaryPatch.open_questions || workspace.open_questions || []).map((q) => `- ${q}`))].join('\n'); return { id: id('dig'), project_id: project.id, workspace_id: workspace.id, version, status: 'confirmed', summary, body, evidence_refs: [...assets.slice(-8).map((a) => `asset:${a.id}`), ...runs.map((r) => `node_run:${r.id}`)], previous_digest_id: previous?.id || null, confirmed_by_user_id: actorId, created_at: now(), updated_at: now() }; }
