import { useCallback, useEffect, useState } from 'react';
import {
  Ban, BadgeCheck, CheckCircle2, FileCheck2, Gauge, LoaderCircle, Play, RefreshCw,
  RotateCcw, ShieldAlert, ShieldCheck, Square, XCircle
} from 'lucide-react';
import { ApiError, apiV2, formatTime, mutateV2, shortHash } from '../../api';
import type { WorkspacePageProps } from '../../workspace';
import { QualityPolicyPanel } from './QualityPolicyPanel';
import { dimensionLabel, errorCodeLabel, kindLabel, statusLabel } from '../../i18n';

type ExecutionRef = { id: string; revision: number; status: string; workflow_id?: string; workflow_revision?: number };
type Asset = { id: string; logical_name: string; asset_kind: string; status: string; current_version: number };
type EvidenceBundle = { assets: Asset[]; traces: Array<{ id: string; trace_type: string; payload_sha256: string; created_at: string }>; digests: Array<{ id: string; digest_type: string; digest_sha256: string; created_at: string }>; test_results: Array<{ id: string; check_id: string; status: string; duration_ms: number; output_sha256: string }>; code_changes: Array<{ id: string; relative_path: string; change_kind: string; before_sha256: string; after_sha256: string }> };
type Dimension = { key: string; label: string; enabled: boolean; weight: number; description?: string };
type HumanReview = { decision: string; weighted_score: number; decision_sha256: string; reasoning: string };
type QualitySelection = { asset_id: string; disposition: 'included' | 'excluded'; exclusion_reason: string; content_sha256: string };
type QualityAdvice = { status: 'valid' | 'invalid' | 'unavailable'; advice: { summary: string; dimensions: Array<{ key: string; rationale: string; suggested_score?: number }>; cautions: string[] }; advice_sha256: string; error_code: string };
type QualityReview = { id: string; status: string; attempt_no: number; asset_ids: string[]; asset_count: number; selections?: QualitySelection[]; input_sha256: string; rubric: { dimensions: Dimension[]; threshold: number }; rubric_sha256: string; threshold: number; advice?: QualityAdvice | null; supersedes_quality_review_id?: string | null; superseded_by_quality_review_id?: string | null; stale_reason?: string; report_id: string | null; report_sha256: string; human_review: HumanReview | null; error_code: string; revision: number; updated_at: string };
type QualityReport = { deterministic_checks: Array<{ asset_id: string; active: boolean; current: boolean; cas_verified: boolean }>; suggestions: Array<{ code: string; asset_id?: string }>; anchors: Array<{ asset_id: string; version_id: string; offset: number; length: number; content_sha256: string }>; anchor_count: number; report_sha256: string };
type EvaluationResult = { requirement_id: string; requirement_key: string; evaluator: string; passed: boolean; blocked: boolean; waived: boolean; actual: unknown; expected: unknown };
type Evaluation = { id: string; generation: number; status: string; requirement_count: number; passed_count: number; score: number; evaluation: { results?: EvaluationResult[] }; evaluation_sha256: string; created_at: string };
type Waiver = { id: string; requirement_id: string | null; action: 'grant' | 'revoke'; revokes_waiver_id: string | null; reason: string; waiver_sha256: string; expires_at: string | null; revision: number; created_at: string };
type Operation = { operation_id: string; resource_id: string; status: string; error_code?: string };

export function ExecutionEvidencePanel({ execution, notify, navigate }: { execution: ExecutionRef; notify: WorkspacePageProps['notify']; navigate: WorkspacePageProps['navigate'] }) {
  const [bundle, setBundle] = useState<EvidenceBundle>({ assets: [], traces: [], digests: [], test_results: [], code_changes: [] });
  const [busy, setBusy] = useState(false); const [fault, setFault] = useState('');
  const load = useCallback(async () => { setBusy(true); try { const result = await apiV2<EvidenceBundle>(`/api/v2/executions/${encodeURIComponent(execution.id)}/evidence`); setBundle(result.data); setFault(''); } catch (error) { report(error, setFault, notify); } finally { setBusy(false); } }, [execution.id, notify]);
  useEffect(() => { void load(); }, [load]);
  const openAsset = (id: string) => { sessionStorage.setItem('aiws:v3:selected-asset', id); navigate('evidence'); };
  return <div className="execution-p7-grid">
    <section className="panel execution-evidence-assets"><Title title="已捕获资产" meta={`${bundle.assets.length} 个已关联`} action={<button className="icon-button" title="刷新执行证据" aria-label="刷新执行证据" onClick={() => void load()}>{busy ? <LoaderCircle className="spin" size={15} /> : <RefreshCw size={15} />}</button>} />{fault && <Fault value={fault} />}<div className="evidence-sublist">{bundle.assets.map((asset) => <button className="evidence-link-row" key={asset.id} onClick={() => openAsset(asset.id)}><FileCheck2 size={15} /><span><strong>{asset.logical_name}</strong><small>{kindLabel(asset.asset_kind)} · v{asset.current_version}</small></span><Status value={asset.status} /></button>)}{!bundle.assets.length && <div className="list-empty">暂无执行资产</div>}</div></section>
    <section className="panel"><Title title="摘要" meta={`${bundle.digests.length} 个已验证`} /><div className="evidence-sublist">{bundle.digests.map((item) => <div key={item.id}><span><strong>{kindLabel(item.digest_type)}</strong><small>{formatTime(item.created_at)}</small></span><code>{shortHash(item.digest_sha256)}</code></div>)}{!bundle.digests.length && <div className="list-empty">暂无摘要</div>}</div></section>
    <section className="panel"><Title title="测试结果" meta={`${bundle.test_results.filter((item) => item.status === 'passed').length}/${bundle.test_results.length} 通过`} /><div className="evidence-sublist">{bundle.test_results.map((item) => <div key={item.id}><span><strong>{item.check_id}</strong><small>{item.duration_ms} 毫秒</small></span><Status value={item.status} /></div>)}{!bundle.test_results.length && <div className="list-empty">暂无测试结果</div>}</div></section>
    <section className="panel"><Title title="追踪" meta={`${bundle.traces.length} 条记录`} /><div className="evidence-sublist">{bundle.traces.map((item) => <div key={item.id}><span><strong>{kindLabel(item.trace_type)}</strong><small>{formatTime(item.created_at)}</small></span><code>{shortHash(item.payload_sha256)}</code></div>)}{!bundle.traces.length && <div className="list-empty">暂无追踪记录</div>}</div></section>
    <section className="panel"><Title title="代码变更" meta={`${bundle.code_changes.length} 个路径`} /><div className="evidence-sublist">{bundle.code_changes.map((item) => <div key={item.id}><span><strong>{item.relative_path}</strong><small>{kindLabel(item.change_kind)}</small></span><code>{shortHash(item.after_sha256 || item.before_sha256)}</code></div>)}{!bundle.code_changes.length && <div className="list-empty">暂无代码变更</div>}</div></section>
  </div>;
}

export function ExecutionQualityPanel({ execution, notify }: { execution: ExecutionRef; notify: WorkspacePageProps['notify'] }) {
  const [reviews, setReviews] = useState<QualityReview[]>([]); const [assets, setAssets] = useState<Asset[]>([]);
  const [selectedId, setSelectedId] = useState(''); const [review, setReview] = useState<QualityReview | null>(null); const [reportValue, setReportValue] = useState<QualityReport | null>(null);
  const [scores, setScores] = useState<Record<string, number>>({}); const [reasons, setReasons] = useState<Record<string, string>>({}); const [decisionReason, setDecisionReason] = useState(''); const [decision, setDecision] = useState<'approved' | 'rejected'>('approved');
  const [excludedReasons, setExcludedReasons] = useState<Record<string, string>>({});
  const [busy, setBusy] = useState(''); const [fault, setFault] = useState('');
  const load = useCallback(async () => {
    const [qualityResult, evidenceResult] = await Promise.all([apiV2<{ quality_reviews: QualityReview[] }>(`/api/v2/executions/${encodeURIComponent(execution.id)}/quality-reviews`), apiV2<EvidenceBundle>(`/api/v2/executions/${encodeURIComponent(execution.id)}/evidence`)]);
    const rows = qualityResult.data.quality_reviews || []; setReviews(rows); setAssets((evidenceResult.data.assets || []).filter((item) => item.status === 'active'));
    setSelectedId((current) => rows.some((item) => item.id === current) ? current : rows[0]?.id || ''); setFault('');
  }, [execution.id]);
  const loadReview = useCallback(async (id = selectedId) => {
    if (!id) { setReview(null); setReportValue(null); return; }
    const value = (await apiV2<{ quality_review: QualityReview }>(`/api/v2/quality-reviews/${encodeURIComponent(id)}`)).data.quality_review;
    setScores(Object.fromEntries(value.rubric.dimensions.filter((item) => item.enabled).map((item) => [item.key, 80])));
    setReasons(Object.fromEntries(value.rubric.dimensions.filter((item) => item.enabled).map((item) => [item.key, ''])));
    setReview(value);
    if (value.report_id) setReportValue((await apiV2<{ report: QualityReport }>(`/api/v2/quality-reviews/${encodeURIComponent(id)}/report`)).data.report); else setReportValue(null);
  }, [selectedId]);
  useEffect(() => { void load().catch((error) => report(error, setFault, notify)); }, [load, notify]);
  useEffect(() => { void loadReview(selectedId).catch((error) => report(error, setFault, notify)); }, [loadReview, notify, selectedId]);
  const start = async () => { const selectedAssets = assets.slice(0, 16); const included = selectedAssets.filter((item) => !Object.hasOwn(excludedReasons, item.id)); if (!included.length) return; setBusy('start'); try { const result = await mutateV2<Operation>(`/api/v2/executions/${encodeURIComponent(execution.id)}/quality-reviews`, { asset_ids: included.map((item) => item.id), asset_selections: selectedAssets.map((item) => Object.hasOwn(excludedReasons, item.id) ? { asset_id: item.id, disposition: 'excluded', exclusion_reason: excludedReasons[item.id] } : { asset_id: item.id, disposition: 'included' }) }, 'POST', execution.revision); const operation = await waitOperation(result.data); if (operation.status !== 'succeeded') throw new Error(operation.error_code || '质量审阅失败'); await load(); setSelectedId(operation.resource_id); notify('质量审阅已就绪'); } catch (error) { report(error, setFault, notify); } finally { setBusy(''); } };
  const mutateReview = async (action: 'cancel' | 'retry') => { if (!review) return; setBusy(action); try { const result = await mutateV2<Operation | { quality_review: QualityReview }>(`/api/v2/quality-reviews/${encodeURIComponent(review.id)}/${action}`, {}, 'POST', review.revision); if (action === 'retry') { const operation = await waitOperation(result.data as Operation); setSelectedId(operation.resource_id); await loadReview(operation.resource_id); } else await loadReview(review.id); await load(); notify(`质量审阅${action === 'cancel' ? '取消' : '重试'}已接受`); } catch (error) { report(error, setFault, notify); } finally { setBusy(''); } };
  const submitDecision = async () => { if (!review) return; setBusy('decision'); try { const dimensions = review.rubric.dimensions.filter((item) => item.enabled).map((item) => ({ key: item.key, score: Number(scores[item.key]), reasoning: reasons[item.key] || '' })); await mutateV2(`/api/v2/quality-reviews/${encodeURIComponent(review.id)}/decision`, { decision, dimensions, reasoning: decisionReason, report_sha256: review.report_sha256, input_sha256: review.input_sha256, rubric_sha256: review.rubric_sha256 }, 'POST', review.revision); await Promise.all([load(), loadReview(review.id)]); notify('质量决策已记录'); } catch (error) { report(error, setFault, notify); } finally { setBusy(''); } };
  const completeDecision = Boolean(decisionReason.trim()) && review?.rubric.dimensions.filter((item) => item.enabled).every((item) => Number.isFinite(scores[item.key]) && Boolean(reasons[item.key]?.trim()));
  const selectionReady = assets.slice(0, 16).some((item) => !Object.hasOwn(excludedReasons, item.id)) && Object.values(excludedReasons).every((reason) => Boolean(reason.trim()));
  return <div className="execution-p7-grid quality-grid-p7">
    <QualityPolicyPanel workflowId={execution.workflow_id} executionId={execution.id} executionRevision={execution.revision} notify={notify} />
    <section className="panel quality-list-panel"><Title title="质量审阅" meta={`${reviews.length} 次不可变运行`} action={<button className="button primary" disabled={!selectionReady || Boolean(busy)} onClick={() => void start()}>{busy === 'start' ? <LoaderCircle className="spin" size={15} /> : <Play size={15} />}开始审阅</button>} />{fault && <Fault value={fault} />}<div className="quality-selection-list">{assets.slice(0, 16).map((asset) => { const excluded = Object.hasOwn(excludedReasons, asset.id); return <div key={asset.id}><label className="quality-selection-toggle"><input type="checkbox" aria-label={`纳入 ${asset.logical_name}`} checked={!excluded} onChange={(event) => setExcludedReasons((current) => { const next = { ...current }; if (event.target.checked) delete next[asset.id]; else next[asset.id] = ''; return next; })} /><span><strong>{asset.logical_name}</strong><small>{asset.asset_kind}</small></span></label>{excluded && <input aria-label={`排除原因 ${asset.logical_name}`} value={excludedReasons[asset.id]} onChange={(event) => setExcludedReasons((current) => ({ ...current, [asset.id]: event.target.value }))} placeholder="填写排除原因" maxLength={500} />}</div>; })}</div><div className="evidence-sublist">{reviews.map((item) => <button className={item.id === selectedId ? 'evidence-link-row selected' : 'evidence-link-row'} key={item.id} onClick={() => setSelectedId(item.id)}><Gauge size={15} /><span><strong>第 {item.attempt_no} 次尝试</strong><small>{item.asset_count} 个资产 · {formatTime(item.updated_at)}{item.superseded_by_quality_review_id ? ' · 已被替代' : ''}</small></span><Status value={item.status} /></button>)}{!reviews.length && <div className="list-empty">暂无质量审阅</div>}</div></section>
    <section className="panel quality-report-panel"><Title title="确定性报告" meta={reportValue ? `${reportValue.anchor_count} 个锚点` : '待处理'} action={review && <div className="row-actions"><button className="icon-button" title="取消质量审阅" aria-label="取消质量审阅" disabled={!['queued', 'preparing', 'checking', 'reviewing'].includes(review.status) || Boolean(busy)} onClick={() => void mutateReview('cancel')}><Square size={14} /></button><button className="icon-button" title="重试质量审阅" aria-label="重试质量审阅" disabled={!['failed', 'cancelled', 'stale'].includes(review.status) || review.attempt_no >= 3 || Boolean(busy)} onClick={() => void mutateReview('retry')}><RotateCcw size={14} /></button></div>} />{review ? <div className="quality-check-list">{review.selections?.filter((item) => item.disposition === 'excluded').map((item) => <div key={item.asset_id}><Ban size={15} /><span><strong>{shortHash(item.asset_id)}</strong><small>{item.exclusion_reason}</small></span></div>)}{reportValue?.deterministic_checks.map((item) => <div key={item.asset_id}>{item.cas_verified && item.active && item.current ? <CheckCircle2 size={15} /> : <XCircle size={15} />}<span><strong>{shortHash(item.asset_id)}</strong><small>CAS {item.cas_verified ? '已验证' : '疑似篡改'} · {item.current ? '当前' : '已过期'}</small></span></div>)}{review.advice && <div className="quality-advice"><ShieldCheck size={15} /><span><strong>模型建议 · {statusLabel(review.advice.status)}</strong><small>{review.advice.advice.summary || review.advice.error_code || '暂无建议结果'}</small></span></div>}{review.error_code && <Fault value={review.error_code} />}{!reportValue && <div className="list-empty">报告待生成</div>}</div> : <div className="list-empty">未选择审阅</div>}</section>
    <section className="panel quality-decision-panel"><Title title="人工决策" meta={review?.human_review ? `${review.human_review.weighted_score} / 100` : review?.status ? statusLabel(review.status) : '暂无审阅'} />{review?.status === 'awaiting_human' ? <div className="quality-decision-form"><div className="segmented" role="group" aria-label="质量决策"><button type="button" className={decision === 'approved' ? 'active' : ''} onClick={() => setDecision('approved')}>批准</button><button type="button" className={decision === 'rejected' ? 'active' : ''} onClick={() => setDecision('rejected')}>拒绝</button></div>{review.rubric.dimensions.filter((item) => item.enabled).map((item) => <div className="quality-score-row" key={item.key}><label><span>{dimensionLabel(item.label || item.key)} · {item.weight}%</span><input aria-label={`${dimensionLabel(item.label || item.key)}评分`} type="number" min="0" max="100" step="1" value={scores[item.key] ?? 80} onChange={(event) => setScores((value) => ({ ...value, [item.key]: Number(event.target.value) }))} /></label><label><span>说明</span><input aria-label={`${dimensionLabel(item.label || item.key)}说明`} value={reasons[item.key] || ''} onChange={(event) => setReasons((value) => ({ ...value, [item.key]: event.target.value }))} /></label></div>)}<label><span>决策说明</span><textarea rows={3} value={decisionReason} onChange={(event) => setDecisionReason(event.target.value)} /></label><button className="button primary" disabled={!completeDecision || Boolean(busy)} onClick={() => void submitDecision()}><BadgeCheck size={15} />记录决策</button></div> : review?.human_review ? <dl className="definition-list compact"><div><dt>决策</dt><dd>{statusLabel(review.human_review.decision)}</dd></div><div><dt>评分</dt><dd>{review.human_review.weighted_score}</dd></div><div><dt>回执</dt><dd className="mono">{shortHash(review.human_review.decision_sha256)}</dd></div><div><dt>说明</dt><dd>{review.human_review.reasoning}</dd></div></dl> : <div className="list-empty">暂无人工决策</div>}</section>
  </div>;
}

export function ExecutionOutcomePanel({ execution, notify }: { execution: ExecutionRef; notify: WorkspacePageProps['notify'] }) {
  const [evaluation, setEvaluation] = useState<Evaluation | null>(null); const [waivers, setWaivers] = useState<Waiver[]>([]); const [reason, setReason] = useState(''); const [requirementId, setRequirementId] = useState(''); const [busy, setBusy] = useState(''); const [fault, setFault] = useState('');
  const load = useCallback(async () => { const result = await apiV2<{ evaluation: Evaluation | null; waivers: Waiver[] }>(`/api/v2/executions/${encodeURIComponent(execution.id)}/outcome`); setEvaluation(result.data.evaluation); setWaivers(result.data.waivers || []); setFault(''); }, [execution.id]);
  useEffect(() => { void load().catch((error) => report(error, setFault, notify)); }, [load, notify]);
  const evaluate = async () => { setBusy('evaluate'); try { const result = await mutateV2<Operation>(`/api/v2/executions/${encodeURIComponent(execution.id)}/outcome/evaluate`, {}, 'POST', execution.revision); const operation = await waitOperation(result.data); if (operation.status !== 'succeeded') throw new Error(operation.error_code || '结果评估失败'); await load(); notify('结果已评估'); } catch (error) { report(error, setFault, notify); } finally { setBusy(''); } };
  const createWaiver = async () => { if (!reason.trim()) return; setBusy('waiver'); try { await mutateV2(`/api/v2/executions/${encodeURIComponent(execution.id)}/outcome/waivers`, { reason, ...(requirementId ? { requirement_id: requirementId } : {}) }, 'POST', execution.revision); setReason(''); await load(); notify('结果豁免已记录'); } catch (error) { report(error, setFault, notify); } finally { setBusy(''); } };
  const revoke = async (waiver: Waiver) => { if (!reason.trim()) return; setBusy(`revoke:${waiver.id}`); try { await mutateV2(`/api/v2/outcome-waivers/${encodeURIComponent(waiver.id)}/revoke`, { reason }, 'POST', 1); setReason(''); await load(); notify('结果豁免已撤销'); } catch (error) { report(error, setFault, notify); } finally { setBusy(''); } };
  const results = evaluation?.evaluation.results || []; const revoked = new Set(waivers.filter((item) => item.action === 'revoke').map((item) => item.revokes_waiver_id)); const grants = waivers.filter((item) => item.action === 'grant');
  return <div className="execution-p7-grid outcome-grid-p7">
    <section className="panel outcome-summary"><Title title="结果" meta={evaluation ? `第 ${evaluation.generation} 代` : '尚未评估'} action={<button className="button primary" disabled={Boolean(busy)} onClick={() => void evaluate()}>{busy === 'evaluate' ? <LoaderCircle className="spin" size={15} /> : <RefreshCw size={15} />}评估</button>} />{fault && <Fault value={fault} />}{evaluation ? <div className="outcome-meter"><div><strong>{evaluation.score}</strong><span>/ 100</span></div><Status value={evaluation.status} /><small>{evaluation.passed_count} / {evaluation.requirement_count} 条要求 · {formatTime(evaluation.created_at)}</small><code>{shortHash(evaluation.evaluation_sha256)}</code></div> : <div className="list-empty">暂无评估</div>}</section>
    <section className="panel outcome-requirements"><Title title="要求" meta={`${results.length} 个确定性结果`} /><div className="outcome-result-list">{results.map((item) => <div key={item.requirement_id}>{item.passed ? <CheckCircle2 size={16} /> : item.waived ? <ShieldCheck size={16} /> : item.blocked ? <Ban size={16} /> : <ShieldAlert size={16} />}<span><strong>{item.requirement_key}</strong><small>{kindLabel(item.evaluator)} · {statusLabel(item.passed ? 'passed' : item.waived ? 'waived' : item.blocked ? 'blocked' : 'gap')}</small></span><code>{renderValue(item.actual)}</code></div>)}{!results.length && <div className="list-empty">暂无要求结果</div>}</div></section>
    <section className="panel outcome-waivers"><Title title="豁免" meta={`${grants.filter((item) => !revoked.has(item.id)).length} 项生效`} /><div className="outcome-waiver-form"><select aria-label="豁免要求" value={requirementId} onChange={(event) => setRequirementId(event.target.value)}><option value="">所有未满足要求</option>{results.filter((item) => !item.passed).map((item) => <option value={item.requirement_id} key={item.requirement_id}>{item.requirement_key}</option>)}</select><input aria-label="豁免原因" value={reason} onChange={(event) => setReason(event.target.value)} placeholder="填写决策原因" /><button className="button" disabled={!reason.trim() || Boolean(busy)} onClick={() => void createWaiver()}><ShieldCheck size={15} />授予豁免</button></div><div className="evidence-sublist">{grants.map((item) => <div key={item.id}><span><strong>{item.requirement_id ? shortHash(item.requirement_id) : '全局豁免'}</strong><small>{revoked.has(item.id) ? '已撤销' : item.expires_at ? `于 ${formatTime(item.expires_at)} 到期` : '生效中'} · {item.reason}</small></span><button className="icon-button" title="撤销豁免" aria-label={`撤销豁免 ${shortHash(item.id)}`} disabled={revoked.has(item.id) || !reason.trim() || Boolean(busy)} onClick={() => void revoke(item)}>{busy === `revoke:${item.id}` ? <LoaderCircle className="spin" size={14} /> : <XCircle size={14} />}</button></div>)}{!grants.length && <div className="list-empty">暂无豁免</div>}</div></section>
  </div>;
}

function Title({ title, meta, action }: { title: string; meta: string; action?: React.ReactNode }) { return <div className="section-title"><div><h2>{title}</h2><span>{meta}</span></div>{action}</div>; }
function Fault({ value }: { value: string }) { return <div className="execution-fault" role="alert"><XCircle size={15} /><span>{errorCodeLabel(value)}</span></div>; }
function Status({ value }: { value: string }) { const tone = ['active', 'completed', 'succeeded', 'passed', 'approved', 'waived'].includes(value) ? 'positive' : ['queued', 'preparing', 'checking', 'reviewing', 'awaiting_human', 'running'].includes(value) ? 'working' : ['failed', 'cancelled', 'stale', 'blocked', 'rejected'].includes(value) ? 'negative' : 'neutral'; return <span className={`status ${tone}`}><span />{statusLabel(value)}</span>; }
async function waitOperation(initial: Operation) { let value = initial; for (let attempt = 0; attempt < 200 && ['accepted', 'queued', 'running', 'paused'].includes(value.status); attempt += 1) { await new Promise((resolve) => setTimeout(resolve, 25)); value = (await apiV2<Operation>(`/api/v2/operations/${encodeURIComponent(value.operation_id)}`)).data; } return value; }
function renderValue(value: unknown) { if (value == null) return '无'; if (typeof value === 'string' || typeof value === 'number') return String(value); return shortHash(JSON.stringify(value)); }
function report(error: unknown, setFault: (value: string) => void, notify: WorkspacePageProps['notify']) { const code = error instanceof ApiError ? error.code : error instanceof Error ? error.message : 'execution_p7_request_failed'; setFault(code); notify(error instanceof Error ? error.message : '执行请求失败', 'error'); }
