import { useEffect, useState } from 'react';
import { Check, LoaderCircle, Save } from 'lucide-react';
import { apiV2, mutateV2 } from '../../api';

type Dimension = { key: string; label: string; enabled: boolean; weight: number; description?: string };
const DEFAULT_DIMENSIONS: Dimension[] = ['coverage', 'accuracy', 'depth', 'consistency', 'clarity'].map((key) => ({ key, label: key[0].toUpperCase() + key.slice(1), enabled: true, weight: 20 }));

export function QualityPolicyPanel({ workflowId, executionId, executionRevision, notify }: { workflowId?: string; executionId?: string; executionRevision?: number; notify: (text: string, tone?: 'ok' | 'error') => void }) {
  const [dimensions, setDimensions] = useState<Dimension[]>(DEFAULT_DIMENSIONS); const [threshold, setThreshold] = useState(80); const [revision, setRevision] = useState(0); const [readiness, setReadiness] = useState<Record<string, unknown> | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  useEffect(() => { if (!workflowId) return; void apiV2<{ policy?: { rubric?: { dimensions?: Dimension[]; threshold?: number }; revision?: number } }>(`/api/v2/workflows/${encodeURIComponent(workflowId)}/quality-policy`).then((result) => { const policy = result.data.policy; if (policy?.rubric?.dimensions?.length) setDimensions(policy.rubric.dimensions); if (policy?.rubric?.threshold != null) setThreshold(Number(policy.rubric.threshold)); setRevision(Number(policy?.revision || 0)); }).catch((caught) => setError(caught instanceof Error ? caught.message : 'Quality policy unavailable')); }, [workflowId]);
  const prepare = async () => { if (!executionId) return; try { const result = await apiV2<Record<string, unknown>>(`/api/v2/executions/${encodeURIComponent(executionId)}/quality-reviews/prepare`); setReadiness(result.data); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Quality readiness unavailable'); } };
  const save = async () => { if (!workflowId) return; setBusy(true); try { await mutateV2(`/api/v2/workflows/${encodeURIComponent(workflowId)}/quality-policy`, { rubric: { schema_version: 'quality.rubric.v1', dimensions, threshold }, threshold }, 'PUT', revision); setRevision((value) => value + 1); notify('Quality policy updated'); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Quality policy update failed'); } finally { setBusy(false); } };
  return <section className="panel quality-policy-panel" data-testid="quality-policy-panel"><div className="section-title"><div><h2>Quality policy</h2><span>Five review dimensions · revision {revision}</span></div><div className="row-actions"><button className="button" onClick={() => void prepare()} disabled={!executionId}>Readiness</button><button className="button primary" onClick={() => void save()} disabled={!workflowId || busy}>{busy ? <LoaderCircle className="spin" size={14} /> : <Save size={14} />}Save</button></div></div><div className="quality-policy-dimensions">{dimensions.map((dimension) => <label key={dimension.key}><input type="checkbox" checked={dimension.enabled} onChange={(event) => setDimensions((rows) => rows.map((row) => row.key === dimension.key ? { ...row, enabled: event.target.checked } : row))} /><span><strong>{dimension.label}</strong><small>{dimension.description || dimension.key}</small></span><input type="number" min="0" max="100" aria-label={`${dimension.label} weight`} value={dimension.weight} onChange={(event) => setDimensions((rows) => rows.map((row) => row.key === dimension.key ? { ...row, weight: Number(event.target.value) } : row))} /></label>)}</div><label className="quality-threshold"><span>Threshold</span><input type="number" min="0" max="100" value={threshold} onChange={(event) => setThreshold(Number(event.target.value))} /></label>{readiness && <div className="quality-readiness" role="status"><Check size={14} />{String((readiness as { readiness?: { ready?: boolean } }).readiness?.ready ? 'Ready for review' : 'Review requires attention')}</div>}{error && <div className="state-banner error" role="alert">{error}</div>}</section>;
}
