import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { parseRemoteUrl } from '../../packages/git-tools/src/index.mjs';
import { inspectMcpConfig } from '../../packages/mcp-bridge/src/index.mjs';
import { CodexRunner, DockerCodexRunner, ensureAgentsBlock } from '../../packages/runner-adapters/src/index.mjs';
import { providerOrder } from '../../packages/context-pack/src/index.mjs';
import { authorityOrder } from '../../packages/memory-policy/src/index.mjs';
import { executeTask, taskNames } from '../../apps/worker/src/index.mjs';

assert.equal(parseRemoteUrl('git@github.com:owner/repo.git').owner, 'owner');
assert.equal(inspectMcpConfig({ name: 'fixture', command: 'node' }).status, 'configured');
const hostArgs = new CodexRunner().buildArgs({ cwd: '.', model: 'gpt-test', promptFile: 'prompt.md', outputSchemaFile: 'schema.json' });
assert.ok(hostArgs.includes('--json'));
assert.ok(hostArgs.includes('gpt-test'));
const dockerArgs = new DockerCodexRunner().buildDockerArgs({ cwd: '/repo', codexHome: '/home/codex', mounts: ['/extra'], outputSchemaFile: '/repo/schema.json' });
assert.deepEqual(dockerArgs.slice(0, 2), ['run', '--rm']);
assert.ok(dockerArgs.includes('aiws-codex-runner:1.4.0-codex-0.144.0'));
assert.ok(dockerArgs.includes('/workspace'));
assert.ok(dockerArgs.includes('CODEX_HOME=/codex-home'));
assert.equal(dockerArgs.includes('OPENAI_API_KEY'), false);
assert.ok(dockerArgs.includes('/extra:/aiws-mounts/0:rw'));
const dockerKeyArgs = new DockerCodexRunner().buildDockerArgs({ cwd: '/repo', codexHome: '/home/codex', mounts: [], outputSchemaFile: '/repo/schema.json', exposeApiKey: true });
assert.ok(dockerKeyArgs.includes('OPENAI_API_KEY'));
assert.ok(providerOrder().includes('node_contract'));
assert.ok(authorityOrder.includes('confirmed_asset_or_decision'));
assert.deepEqual(taskNames, ['context-pack.build', 'node-run.execute']);
await assert.rejects(() => executeTask('unknown.task', {}), /unsupported_worker_task/);

const repo = fs.mkdtempSync(path.join(os.tmpdir(), 'aiws-agents-'));
fs.writeFileSync(path.join(repo, 'AGENTS.md'), '# User Rules\n\nKeep this.\n', 'utf8');
const result = ensureAgentsBlock(repo);
assert.equal(result.changed, true);
const agents = fs.readFileSync(path.join(repo, 'AGENTS.md'), 'utf8');
assert.ok(agents.includes('Keep this.'));
assert.ok(agents.includes('AIWS:BEGIN'));
assert.ok(agents.includes('Confirmed Asset'));
fs.rmSync(repo, { recursive: true, force: true });
console.log('package facade tests passed');
